### ISSUE TITLE
new grid: 'argentina_grid2' (AR)

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#102]
This grid is based on [argentina_grid1](https://hafen.github.io/geofacet/rd.html#grids_1) with two changes. Juridically "Islas Malvinas" and "Antartida Argetnina" are formally included in Tierra del Fuego Province. And practically, most times we are not going to plot data from those geographic units.

Example: Efective Number of Competing Parties (ENCP)-> https://github.com/TuQmano/geofacet_ARG/tree/master/ARGENTINA

Grid data:

```
"col","row","code","name_es"
1,1,"AR-Y","Jujuy"
3,2,"AR-P","Formosa"
5,2,"AR-N","Misiones"
1,2,"AR-A","Salta"
2,2,"AR-T","Tucumán"
1,3,"AR-K","Catamarca"
3,3,"AR-H","Chaco"
4,3,"AR-W","Corrientes"
2,3,"AR-G","Santiago.del.Estero"
2,4,"AR-X","Córdoba"
4,4,"AR-E","Entre.Ríos"
1,4,"AR-F","La.Rioja"
3,4,"AR-S","Santa.Fe"
3,5,"AR-B","Buenos.Aires"
4,5,"AR-C","C.A.B.A."
1,5,"AR-J","San.Juan"
2,5,"AR-D","San.Luis"
2,6,"AR-L","La.Pampa"
1,6,"AR-M","Mendoza"
1,7,"AR-Q","Neuquén"
2,7,"AR-R","Río.Negro"
1,8,"AR-U","Chubut"
1,9,"AR-Z","Santa.Cruz"
1,10,"AR-V","Tierra.del.Fuego"
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Map_of_Argentina_with_provinces_names_en.png)

**Comment by stedy** [comment]
This grid was added to [geofacet release 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
