### ISSUE TITLE
new grid: 'Bloomberg Cartogram 1'

### ISSUE THREAD

**Issue by christophercannon** [hafen/geofacet#104]
11 X 8 grid, AK and HI flush with CA

row,col,code,name
7,7,AL,Alabama
1,1,AK,Alaska
6,2,AZ,Arizona
6,5,AR,Arkansas
5,1,CA,California
5,3,CO,Colorado
4,10,CT,Connecticut
5,10,DE,Delaware
8,9,FL,Florida
7,8,GA,Georgia
8,1,HI,Hawaii
3,2,ID,Idaho
4,6,IL,Illinois
5,6,IN,Indiana
4,5,IA,Iowa
6,4,KS,Kansas
6,6,KY,Kentucky
7,5,LA,Louisiana
1,11,ME,Maine
5,9,MD,Maryland
3,10,MA,Massachusetts
3,7,MI,Michigan
3,5,MN,Minnesota
7,6,MS,Mississippi
5,5,MO,Missouri
3,3,MT,Montana
5,4,NE,Nebraska
5,2,NV,Nevada
2,11,NH,New Hampshire
4,9,NJ,New Jersey
6,3,NM,New Mexico
3,9,NY,New York
6,9,NC,North Carolina
3,4,ND,North Dakota
4,7,OH,Ohio
7,4,OK,Oklahoma
4,1,OR,Oregon
4,8,PA,Pennsylvania
3,11,RI,Rhode Island
6,8,SC,South Carolina
4,4,SD,South Dakota
6,7,TN,Tennessee
8,4,TX,Texas
4,2,UT,Utah
2,10,VT,Vermont
5,8,VA,Virginia
3,1,WA,Washington
5,7,WV,West Virginia
3,6,WI,Wisconsin
4,3,WY,Wyoming

[bloomberg-cartogram1.pdf](https://github.com/hafen/geofacet/files/1881011/bloomberg-cartogram1.pdf)

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/a/a5/Map_of_USA_with_state_names.svg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
