### ISSUE TITLE
new grid: 'AR - Buenos Aires Province (PBA) Electoral Districts'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#107]
Buenos Aires Province has more than a hundred and thirty muncipalities and many geographic divisions. For electoral purposes we can focus on it´s 8 electoral districts ("[secciones electorales](https://es.wikipedia.org/wiki/Secciones_electorales_de_la_provincia_de_Buenos_Aires)" in spanish).

Example: [2017 National Elections results](https://github.com/TuQmano/geofacet_ARG/tree/master/PBA) (by electoral districts). 

Grid data:

```
"name","code","row","col"
"Segunda"," 2",1,2
"Primera"," 1",1,3
"Tercera"," 3",1,4
"Capital"," CAP",2,4
"Septima"," 7",2,2
"Cuarta"," 4",2,1
"Quinta"," 5",2,3
"Sexta"," 6",3,1
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Secciones_electorales_de_la_provincia_de_Buenos_Aires.svg/800px-Secciones_electorales_de_la_provincia_de_Buenos_Aires.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
