### ISSUE TITLE
new grid: 'UR-Uruguay Departments'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#108]
Uruguay political division

Example: 2014 Elections: https://github.com/TuQmano/geofacet_ARG/tree/master/zExtra_URUGUAY
Source data: http://www.montevideo.com.uy/Noticias/Datos-de-la-Corte-Electoral-por-departamento-uc251040

Grid data:

```
"name","code","row","col"
"Artigas","Artigas",1,2
"Rivera","Rivera",2,3
"Salto","Salto",2,2
"Cerro Largo","Cerro Largo",3,4
"Paysandu","Paysandú",3,2
"Tacuarembo","Tacuarembó",3,3
"Durazno","Durazno",4,3
"Rio Negro","Río Negro",4,2
"Treinta y Tres","Treinta y Tres",4,4
"Flores","Flores",5,2
"Florida","Florida",5,3
"Lavalleja","Lavalleja",5,4
"Rocha","Rocha",5,5
"Soriano","Soriano",5,1
"Canelones","Canelones",6,3
"Colonia","Colonia",6,1
"Maldonado","Maldonado",6,4
"San Jose","San José",6,2
"Montevideo","Montevideo",7,3
```

**Comment by stedy** [comment]
![](https://mapamundi.online/wp-content/uploads/2018/11/mapa-politico-de-uruguay.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
