### ISSUE TITLE
GUI for creating grids. 

### ISSUE THREAD

**Issue by eliocamp** [hafen/geofacet#11]
Creating a grid is not an exact science and probably most of the time there will be the need for manual tweaking. How about integrating a tool for creating a grid? 

I've tried something here: https://ecamp.shinyapps.io/grid_create/

It's barely usable, the leftmost table doesn't update and there's not way to download the new grid or to add or remove codes. But it's only a start. What do you think?

**Comment by hafen** [comment]
This is a great idea - thanks! I started on an idea like this a little while back but this prompted me to revive it. I'll probably have something to put up tomorrow along these lines for a look.

**Comment by eliocamp** [comment]
Cool!
This kind of package would be very useful in my field (atmospheric sciences).

**Comment by hathawayj** [comment]
Turns out atmospheric science was the original driver of the idea when we first came up with the visualization at PNNL.

**Comment by eliocamp** [comment]
Excellent.
I'm sure it will be very useful for visualizing meteograms, climographs and whatnot.

**Comment by hafen** [comment]
I've pushed out an app to do this. It's available [here](https://hafen.github.io/grid-designer/) or to see it already populated with an example, try [this link](https://hafen.github.io/grid-designer/#img=http%3A%2F%2F1.bp.blogspot.com%2F-DztsF0ghmtE%2FT3r-Y1M-VPI%2FAAAAAAAAAss%2F-hYbi2iORz8%2Fs1600%2Fusa-map-region.gif&data=row%2Ccol%2Ccode%2Cname%0A1%2C11%2CME%2CMaine%0A1%2C10%2CNH%2CNew%20Hampshire%0A1%2C9%2CVT%2CVermont%0A1%2C6%2CWI%2CWisconsin%0A2%2C2%2CID%2CIdaho%0A2%2C6%2CIL%2CIllinois%0A2%2C10%2CMA%2CMassachusetts%0A2%2C7%2CMI%2CMichigan%0A2%2C5%2CMN%2CMinnesota%0A2%2C3%2CMT%2CMontana%0A2%2C9%2CNY%2CNew%20York%0A2%2C4%2CND%2CNorth%20Dakota%0A2%2C1%2CWA%2CWashington%0A3%2C10%2CCT%2CConnecticut%0A3%2C6%2CIN%2CIndiana%0A3%2C5%2CIA%2CIowa%0A3%2C2%2CNV%2CNevada%0A3%2C9%2CNJ%2CNew%20Jersey%0A3%2C7%2COH%2COhio%0A3%2C1%2COR%2COregon%0A3%2C8%2CPA%2CPennsylvania%0A3%2C11%2CRI%2CRhode%20Island%0A3%2C4%2CSD%2CSouth%20Dakota%0A3%2C3%2CWY%2CWyoming%0A4%2C1%2CCA%2CCalifornia%0A4%2C3%2CCO%2CColorado%0A4%2C10%2CDE%2CDelaware%0A4%2C6%2CKY%2CKentucky%0A4%2C9%2CMD%2CMaryland%0A4%2C5%2CMO%2CMissouri%0A4%2C4%2CNE%2CNebraska%0A4%2C2%2CUT%2CUtah%0A4%2C8%2CVA%2CVirginia%0A4%2C7%2CWV%2CWest%20Virginia%0A5%2C2%2CAZ%2CArizona%0A5%2C5%2CAR%2CArkansas%0A5%2C4%2CKS%2CKansas%0A5%2C3%2CNM%2CNew%20Mexico%0A5%2C7%2CNC%2CNorth%20Carolina%0A5%2C8%2CSC%2CSouth%20Carolina%0A5%2C6%2CTN%2CTennessee%0A5%2C9%2CDC%2CDistrict%20of%20Columbia%0A6%2C7%2CAL%2CAlabama%0A6%2C8%2CGA%2CGeorgia%0A6%2C5%2CLA%2CLouisiana%0A6%2C6%2CMS%2CMississippi%0A6%2C4%2COK%2COklahoma%0A7%2C2%2CAK%2CAlaska%0A7%2C9%2CFL%2CFlorida%0A7%2C1%2CHI%2CHawaii%0A7%2C4%2CTX%2CTexas). You can click and drag to move things around or edit the csv to add/remove entities.

<img width="1390" alt="screen shot 2017-06-16 at 1 14 24 pm" src="https://user-images.githubusercontent.com/1275592/27243245-d5db15cc-5295-11e7-88bc-16f7f3c39da7.png">

You can also access it from the package now. For example, if you want to modify an existing grid:

```r
grid_design(data = aus_grid1, img = "http://www.john.chapman.name/Austral4.gif")
```

**Comment by eliocamp** [comment]
Much better than anything that I could come up with!

**Comment by hafen** [comment]
Thanks! I'll close this.
