### ISSUE TITLE
new grid: '(AR) Mendoza province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#111]
Mendoza (ARGENTINA) political division 

Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_Mendoza_por_poblaci%C3%B3n

Grid data:

```
"name","code","row","col"
"Las Heras","Las Heras",1,3
"Lavalle","Lavalle",1,4
"Guaymallén","Guaymallén",2,4
"Godoy Cruz","Godoy Cruz",2,3
"Lujan de Cuyo","Lujan de Cuyo",2,1
"Capital","Capital",2,2
"Maipu","Maipu",3,3
"San Martin","San Martin",3,5
"Tupungato","Tupungato",3,2
"Junin","Junin",3,4
"Tunuyan","Tunuyan",4,2
"La Paz","La Paz",4,5
"Santa Rosa","Santa Rosa",4,4
"Rivadavia","Rivadavia",4,3
"San Carlos","San Carlos",5,2
"General Alvear","General Alvear",5,4
"San Rafael","San Rafael",5,3
"Malargue","Malargue",6,1
```

**Comment by stedy** [comment]
![[](https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Mapa_de_la_divisi%C3%B3n_pol%C3%ADtica_de_la_pcia._de_Menoza_-Argentina-.jpg/800px-Mapa_de_la_divisi%C3%B3n_pol%C3%ADtica_de_la_pcia._de_Menoza_-Argentina-.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
