### ISSUE TITLE
new grid: '(AR) San Juan province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#114]
San Juan (ARGENTINA) political division

Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_San_Juan_por_poblaci%C3%B3n

Grid data:

```
"name","code","row","col"
"Iglesia","Iglesia",2,2
"Jáchal","Jáchal",2,3
"Valle Fértil","Valle Fértil",2,4
"Ullum","Ullum",3,3
"Albardón","Albardón",3,4
"Angaco","Angaco",3,5
"Zonda","Zonda",4,3
"San Martín","San Martín",4,4
"Caucete","Caucete",4,5
"Rivadavia","Rivadavia",5,3
"Chimbas","Chimbas",5,4
"San Lucía","San Lucía",5,5
"Pocito","Pocito",6,3
"Capital","Capital",6,4
"9 de Julio","10 de Julio",6,5
"Calingasta","Calingasta",6,2
"Rawson","Rawson",7,4
"25 de Mayo","26 de Mayo",7,5
"Sarmiento","Sarmiento",8,4
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mapa_de_la_Provincia_de_San_Juan_%28Argentina%29_con_divisi%C3%B3n_pol%C3%ADtica.jpg/500px-Mapa_de_la_Provincia_de_San_Juan_%28Argentina%29_con_divisi%C3%B3n_pol%C3%ADtica.jpg)

**Comment by stedy** [comment]
I fixed both of these lines to be the same in both columns

"9 de Julio","10 de Julio",6,5
"25 de Mayo","26 de Mayo",7,5

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
