### ISSUE TITLE
new grid: '(AR) San Luis province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#115]
San Luis (ARGENTINA) political division

Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_San_Luis_por_poblaci%C3%B3n

Grid data:

```
"name","code","row","col"
"Ayacucho","Ayacucho",1,2
"Junin","Junin",1,3
"Belgrano","Belgrano",2,1
"Chacabuco","Chacabuco",2,3
"Libertador General San Martin","Libertador General San Martin",2,2
"Coronel Pringles","Coronel Pringles",3,2
"General Pedernera","General Pedernera",3,3
"Juan Martin de Pueyrredon","Juan Martin de Pueyrredon",3,1
"Gobernador Dupuy","Gobernador Dupuy",4,3
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/a/a4/Divisi%C3%B3n_pol%C3%ADtica_de_la_Provincia_de_San_Luis_-Argentina-.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
