### ISSUE TITLE
new grid: '(AR) Neuquen province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#116]
Neuquen (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Neuqu%C3%A9n

Grid data:

```
name,code,row,col
Chos Malal,Chos Malal,1,3
Minas,Minas,1,2
Pehuenches,Pehuenches,1,4
Añelo,Añelo,2,4
Loncopué,Loncopué,2,3
Ñorquín,Ñorquín,2,2
Confluencia,Confluencia,3,4
Picunches,Picunches,3,2
Zapala,Zapala,3,3
Alumine,Alumine,4,1
Catán Lil,Catán Lil,4,2
Picún Leufú,Picún Leufú,4,3
Collón Curá,Collón Curá,5,2
Huiliches,Huiliches,5,1
Lácar,Lácar,6,1
Los Lagos,Los Lagos,7,1
```

![map](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Mapa_de_densidad_de_poblacion_2010_provincia_del_neuquen.svg/250px-Mapa_de_densidad_de_poblacion_2010_provincia_del_neuquen.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
