### ISSUE TITLE
new grid: '(AR) Jujuy province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#117]
Jujuy (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Jujuy

Grid data:

```
name,code,row,col
Yavi,Yavi,2,3
Santa Catalina,Santa Catalina,2,2
Humahuaca,Humahuaca,3,3
Rinconada,Rinconada,3,1
Cochinoca,Cochinoca,3,2
Valle Grande,Valle Grande,3,4
Ledesma,Ledesma,4,5
Susques,Susques,4,1
Tumbaya,Tumbaya,4,3
Tilcara,Tilcara,4,4
Santa Bárbara,Santa Bárbara,5,5
Dr. Manuel Belgrano,Dr. Manuel Belgrano,5,3
Palpalá,Palpalá,5,4
San Pedro,San Pedro,6,5
San Antonio,San Antonio,6,3
El Carmen,El Carmen,6,4
```

![map](http://www.dipec.jujuy.gov.ar/mapas_jujuy_censo/jujuydepartamentos.gif)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by hafen** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Cochinoca_%28Provincia_de_Jujuy_-_Argentina%29.svg/2560px-Cochinoca_%28Provincia_de_Jujuy_-_Argentina%29.svg.png)
