### ISSUE TITLE
new grid: '(AR) Catamarca province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#118]
Catamarca (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Catamarca
Grid data:

```
name,code,row,col
Antofagasta de la Sierra,Antofagasta de la Sierra,1,1
Santa María,Santa María,2,3
Belén,Belén,2,2
Tinogasta,Tinogasta,2,1
Andalgalá,Andalgalá,3,3
Paclín,Paclín,3,5
Santa Rosa,Santa Rosa,3,6
Ambato,Ambato,3,4
Pomán,Pomán,4,3
El Alto,El Alto,4,6
Fray Mamerto Esquiú,Fray Mamerto Esquiú,4,5
Capital,Capital,4,4
Ancasti,Ancasti,5,6
Valle Viejo,Valle Viejo,5,5
Capayán,Capayán,5,4
La Paz,La Paz,6,7
```

![map](http://www.all-argentina.com.ar/wp-content/uploads/mapa-politico-catamarca.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by hafen** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Ambato_%28Provincia_de_Catamarca_-_Argentina%29.svg/1920px-Ambato_%28Provincia_de_Catamarca_-_Argentina%29.svg.png)
