### ISSUE TITLE
new grid: 'br_grid1'

### ISSUE THREAD

**Issue by italocegatta** [hafen/geofacet#12]
Grid for the 27 states of Brazil. 

# Grid data:
```
br_grid1 <- tribble(
  ~row, ~col, ~code, ~name,
  1, 2, "RR", "Roraima",
  1, 3, "AP", "Amapá",
  2, 2, "AM", "Amazonas",
  2, 3, "PA", "Pará",
  2, 4, "MA", "Maranhão",
  2, 5, "CE", "Ceará",
  3, 1, "AC", "Acre",
  3, 3, "TO", "Tocantins",
  3, 4, "PI", "Piauí",
  3, 5, "PB", "Paraíba",
  3, 6, "RN", "Rio Grande do Norte",
  3, 2, "RO", "Rondônia",
  4, 2, "MT", "Mato Grosso",
  4, 5, "PE", "Pernambuco",
  4, 6, "AL", "Alagoas",
  4, 3, "GO", "Goiás",
  5, 3, "DF", "Distrito Federal",
  5, 4, "MG", "Minas Gerais",
  4, 4, "BA", "Bahia",
  5, 5, "SE", "Sergipe",
  5, 2, "MS", "Mato Grosso do Sul",
  6, 5, "ES", "Espírito Santo",
  7, 3, "PR", "Paraná",
  6, 3, "SP", "São Paulo",
  6, 4, "RJ", "Rio de Janeiro",
  7, 4, "SC", "Santa Catarina",
  8, 3, "RS", "Rio Grande do Sul"
)
```

# Reference
![reference](http://cejeduinfantil.pbworks.com/f/1458041984/MapaBrasilSiglas.gif)

# Exemple code
```
library(ggplot2)
library(geofacet)
library(tibble)
library(readr)

df <- read_csv2("https://raw.githubusercontent.com/italocegatta/italocegatta.github.io_source/master/content/dados/chuva_estados.csv")

ggplot(df, aes(mes, ppt)) +
  geom_col() +
  facet_geo(~estado, grid = br_grid1) +
  labs(
    x = "Month", y = "Rain (mm)"
  ) +
  scale_x_continuous(breaks = seq(1, 12, 1)) +
  scale_y_continuous(breaks = seq(100, 600, 200)) +
  theme_bw(14) +
  theme(
    axis.title = element_text(size = 18),
    panel.grid.minor.x = element_blank()
  )
```
![br_grid1](https://user-images.githubusercontent.com/17628175/27253973-f218b392-5354-11e7-8fce-538a33d894e9.png)

**Comment by hafen** [comment]
Thanks! I like this example. Can I include the dataset as well in the package? If so, what is the source?

**Comment by hafen** [comment]
Added. Thanks!

**Comment by italocegatta** [comment]
Hi! Thanks for add the grid.

this is the repo that I toke the dataset [http://www.ipef.br/geodatabase/](). 
The directy link is [here].(http://www.ipef.br/geodatabase/repository/651da1d8va615cz1ad1da8s4rq8146a1dsa2132c1zn1/Koppen_Brazil_2013.rar)
You can get a tidy table in this [link](https://raw.githubusercontent.com/italocegatta/italocegatta.github.io_source/master/content/dados/chuva_estados.csv). I selected only temperature from the dataset.

##  Notes from the full dataset (by author)
This spreadsheet contains a database climate for each of Brazilian municipalities.
The values of altitude, temperature, and rainfall represent the average of the pixels (100 m) within the perimeter of each municipality.
Only the most representative Köppen climate type (% in area) was considered in each municipality.

Reference:
Alvares, C.A., Stape, J.L., Sentelhas, P.C., Gonçalves, J.L.M.; Sparovek, G., 2013. Köppen’s climate classification map for Brazil. Meteorologische Zeitschrift, DOI: http://dx.doi.org/10.1127/0941-2948/2013/0507
