### ISSUE TITLE
new grid: '(AR) Formosa province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#120]
Formosa (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Formosa

Grid data:

```
name,code,row,col
Ramón Lista,Ramón Lista,1,1
Bermejo,Bermejo,2,2
Matacos,Matacos,2,1
name,Patiño,2,3
Pilagás,Pilagás,2,4
Pilcomayo,Pilcomayo,2,5
Formosa,Formosa,3,5
Pirané,Pirané,3,4
Laishí,Laishí,4,5
```

![map](http://www.tempusagro.com.ar/img/formosa/divisionpolitica.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
