### ISSUE TITLE
new grid: '(AR) Santiago_del_Esterio province'new grid

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#121]
Santiago del Estero (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_Santiago_del_Estero_por_poblaci%C3%B3n

Grid data:

```
name,code,row,col
Copo,Copo,1,4
Pellegrini,Pellegrini,1,3
Alberdi,Alberdi,2,4
Jiménez,Jiménez,2,3
Banda,Banda,3,3
Figueroa,Figueroa,3,4
Moreno,Moreno,3,5
Río Hondo,Río Hondo,3,2
Capital,Capital,4,2
Juan F. Ibarra,Juan F. Ibarra,4,5
Robles,Robles,4,3
Sarmiento,Sarmiento,4,4
Guasayán,Guasayán,4,1
Avellaneda,Avellaneda,5,4
Belgrano,General Taboada,5,5
San Martín,San Martín,5,3
Silípica,Silípica,5,2
Choya,Choya,5,1
Atamisqui,Atamisqui,6,3
Belgrano,Belgrano,6,5
Loreto,Loreto,6,2
Salavina,Salavina,6,4
Aguirre,Aguirre,7,5
Ojo de Agua,Ojo de Agua,7,2
Quebrachos,Quebrachos,7,3
Mitre,Mitre,7,4
Rivadavia,Rivadavia,8,5
```

![map](https://t4.kn3.net/taringa/0/8/1/6/6/1/Meeekii/618.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by hafen** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/b/b8/Departamento_Aguirre_%28Santiago_del_Estero_-_Argentina%29.png)
