### ISSUE TITLE
Beijing

### ISSUE THREAD

**Issue by zouhx11** [hafen/geofacet#122]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
name,row,col
密云区,1,6
怀柔区,1,5
延庆区,1,4
顺义区,2,5
平谷区,2,6
昌平区,2,3
门头沟区,3,1
海淀区,3,2
西城区,3,3
东城区,3,4
朝阳区,3,5
通州区,3,6
大兴区,4,4
房山区,4,1
丰台区,4,3
石景山区,4,2
```

![map](https://gss0.bdstatic.com/-4o3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike150%2C5%2C5%2C150%2C50/sign=49d612774d10b912abccfeaca2949766/d043ad4bd11373f006c53a53ae0f4bfbfaed0407.jpg)

**Comment by zouhx11** [comment]
R code:
mygrid <- data.frame(
  name = c("密云区", "怀柔区", "延庆区", "顺义区", "平谷区", "昌平区", "门头沟区", "海淀区", "西城区", "东城区", "朝阳区", "通州区", "大兴区", "房山区", "丰台区", "石景山区"),
  row = c(1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4),
  col = c(6, 5, 4, 5, 6, 3, 1, 2, 3, 4, 5, 6, 4, 1, 3, 2),
  stringsAsFactors = FALSE
)
geofacet::grid_preview(mygrid)

**Comment by zouhx11** [comment]
data.frame(
  name = c("MiYun", "HuaiRou", "YanQing", "ShunYi", "PingGu", "ChangPing", "MenTouGou", "HaiDian", "XiCheng", "DongCheng", "ChaoYang", "TongZhou", "DaXing", "FangShan", "FengTai", "ShiJingShan"),
  code = c("密云区", "怀柔区", "延庆区", "顺义区", "平谷区", "昌平区", "门头沟区", "海淀区", "西城区", "东城区", "朝阳区", "通州区", "大兴区", "房山区", "丰台区", "石景山区"),
  row = c(1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4),
  col = c(6, 5, 4, 5, 6, 3, 1, 2, 3, 4, 5, 6, 4, 1, 3, 2),
  stringsAsFactors = FALSE
)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
