### ISSUE TITLE
new grid: '(AR) Chubut province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#124]
Chubut (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_del_Chubut

Grid data:

```
name,code,row,col
Biedma,Biedma,1,5
Gastre,Gastre,1,3
Telsen,Telsen,1,4
Cushamen,Cushamen,1,2
Futaleufú,Futaleufú,2,1
Gaiman,Gaiman,2,3
Rawson,Rawson,2,4
Languiñeo,Languiñeo,2,2
Mártires,Mártires,3,3
Paso de Indios,Paso de Indios,3,2
Tehuelches,Tehuelches,3,1
Florentino Ameghino,Florentino Ameghino,3,4
Río Senguer,Río Senguer,4,1
Escalante,Escalante,4,3
Sarmiento,Sarmiento,4,2
```

![map](https://espanol.mapsofworld.com/wp-content/uploads/2014/06/mapa-de-chubut.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
