### ISSUE TITLE
new grid: '(AR) Tierra_del_Fuego province'

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#126]
Tierra del Fuego (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Tierra_del_Fuego,_Ant%C3%A1rtida_e_Islas_del_Atl%C3%A1ntico_Sur

Grid data:

```
name,code,row,col
Río Grande,Río Grande,2,1
Tolhuin,Tolhuin,3,2
Ushuaia,Ushuaia,4,1
Antártida Argentina,Antártida Argentina,6,3
```

![map](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Tierra-del-fuego-s.jpg/300px-Tierra-del-fuego-s.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
