### ISSUE TITLE
new grid: '(AR) Santa_Cruz province' 

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#128]
Santa Cruz  (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Santa_Cruz_(Argentina)

Grid data:

```
name,code,row,col
Deseado,Deseado,1,2
Lago Buenos Aires,Lago Buenos Aires,1,1
Magallanes,Magallanes,2,2
Río Chico,Río Chico,2,1
Corpen Aike,Corpen Aike,3,2
Lago Argentino,Lago Argentino,3,1
Güer Aike,Güer Aike,4,2
```

![map](http://2.bp.blogspot.com/-KtWBO9BmY-4/TvvL1UcUA-I/AAAAAAAAADc/uwWlJLjZl18/s1600/departamentos.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
