### ISSUE TITLE
new grid: '(AR) Entre_Ríos province' 

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#130]
Misiones (ARGENTINA) political division
Reference: https://es.wikipedia.org/wiki/Anexo:Departamentos_de_la_provincia_de_Entre_R%C3%ADos

Grid data:

```
name,code,row,col
Federación,Federación,1,4
Feliciano,Feliciano,1,3
Concordia,Concordia,2,4
Federal,Federal,2,3
La Paz,La Paz,2,2
Colón,Colón,3,4
Paraná,Paraná,3,1
San Salvador,San Salvador,3,3
Villaguay,Villaguay,3,2
Diamante,Diamante,4,1
Nogoyá,Nogoyá,4,2
Tala,Tala,4,3
Uruguay,Uruguay,4,4
Gualeguay,Gualeguay,5,3
Gualeguaychú,Gualeguaychú,5,4
Victoria,Victoria,5,2
Islas del Ibicuy,Islas del Ibicuy,6,4
```

![map](http://www.entremediosweb.com/wp-content/uploads/2017/10/mapa.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
