### ISSUE TITLE
new grid: 'nl_provinces_grid1'

### ISSUE THREAD

**Issue by bvhest** [hafen/geofacet#131]
Definition of a grid with the provinces of The Netherlands that can be used with the R geofacet package.

Reference map:
https://upload.wikimedia.org/wikipedia/commons/3/30/NederlandseProvinciesLarge.png

Example code (with comments/variable names in Dutch) in the code-directory at:
https://github.com/bvhest/geofacet_nl/

Grid data:

```
"row","col","code","name"
1,4,"Gr","Groningen"
1,3,"Fr","Friesland"
2,4,"Dr","Drenthe"
3,4,"Ov","Overijssel"
3,3,"Fl","Flevoland"
3,2,"NH","Noord-Holland"
4,4,"Ge","Gelderland"
4,3,"Ut","Utrecht"
4,2,"ZH","Zuid-Holland"
5,3,"NB","Noord-Brabant"
5,1,"Ze","Zeeland"
6,4,"Li","Limburg"
```

**Comment by edwindj** [comment]
:+1:  I discovered your submission, just after I finished my attempt (#134)

However I think it is a good thing to have layout choices (hence `_grid2`) and to have code that directly connect to cbs data.
