### ISSUE TITLE
new grid: 'nl_prov_cbs_grid2'

### ISSUE THREAD

**Issue by edwindj** [hafen/geofacet#134]
Definition of a grid with the provinces of The Netherlands that can be used with the R geofacet package.
It provides codes that are used by the statistical institute of NL ([Statistics Netherlands/CBS](http://www.cbs.nl)). 
It differs from suggested grid #131 in the following aspects:

- a slightly different layout
- uses cbs codes that can be used with their data e.g. [cbsodataR](https://cran.r-project.org/package=cbsodataR). (note that `code_cbs` contains whitespace in the codes. `code_cbs2` are the trimmed codes.
- provides a column with abbreviation according to dictionary ("van Dale")

Grid data:

```
"name","code","code_cbs","code_cbs2","row","col"
"Groningen","GR","PV20  ","PV20",1,5
"Friesland","FR","PV21  ","PV21",1,4
"Drenthe","DR","PV22  ","PV22",2,5
"Noord-Holland","NH","PV27  ","PV27",3,2
"Flevoland","FL","PV24  ","PV24",3,4
"Overijssel","OV","PV23  ","PV23",3,5
"Zuid-Holland","ZH","PV28  ","PV28",4,2
"Utrecht","UT","PV26  ","PV26",4,3
"Gelderland","GD","PV25  ","PV25",4,4
"Zeeland","ZL","PV29  ","PV29",5,1
"Noord-Brabant","NB","PV30  ","PV30",5,3
"Limburg","LB","PV31  ","PV31",6,4
```

![map](https://upload.wikimedia.org/wikipedia/commons/3/30/NederlandseProvinciesLarge.png)

## code example

```r
library(cbsodataR) # R package to retrieve data via API Statistics Netherlands
library(tidyverse)

cbs_get_data("83523NED") %>% 
  cbs_add_date_column() %>% 
  filter(Perioden_freq == "Q", grepl("^PV", RegioS)) %>% # get province quaterly data
  rename(prov = RegioS, quarter = Perioden_Date, self_employed = Zelfstandige_5) %>% 
  ggplot(aes(x = quarter, y = self_employed)) + 
    geom_line() +
    facet_geo(~prov, grid = nl_prov_cbs_grid2, label = "name")
```
produces:

![geofacet](https://user-images.githubusercontent.com/542492/42750343-38918f92-88e7-11e8-8fdb-38139f5df613.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
