### ISSUE TITLE
new grid: 'mx_state_grid3'

### ISSUE THREAD

**Issue by fazepher** [hafen/geofacet#135]
This issue suggests a new geofacet grid for displaying Mexican states. It aims at improving the 2 existing grids with a "better" (at least in my opinion) representation, specially when it comes to both peninsules. 

Grid data: 
"row","col","code","name","code_edo"
1,1,"BC","Baja California","02"
1,2,"SON","Sonora","26"
1,3,"CHIH","Chihuahua","08"
1,4,"COAH","Coahuila","05"
1,5,"NL","Nuevo León","19"
1,6,"TAM","Tamaulipas","28"
2,1,"BCS","Baja California Sur","03"
2,3,"SIN","Sinaloa","25"
2,4,"DGO","Durango","10"
2,5,"ZAC","Zacatecas","32"
2,6,"SLP","San Luis Potosí","24"
3,4,"NAY","Nayarit","18"
3,5,"AGS","Aguascalientes","01"
3,6,"GTO","Guanajuato","11"
3,7,"HGO","Hidalgo","13"
4,4,"COL","Colima","06"
4,5,"JAL","Jalisco","14"
4,6,"QRO","Querétaro","22"
4,7,"CDMX","Ciudad de México","09"
4,8,"PUE","Puebla","21"
4,11,"YUC","Yucatan","31"
4,12,"QROO","Quintana Roo","23"
5,5,"MICH","Michoacán","16"
5,6,"MEX","Estado de México","15"
5,7,"MOR","Morelos","17"
5,8,"TLAX","Tlaxcala","29"
5,9,"VER","Veracruz","30"
5,10,"TAB","Tabasco","27"
5,11,"CAMP","Campeche","04"
6,7,"GRO","Guerrero","12"
6,8,"OAX","Oaxaca","20"
6,9,"CHPS","Chiapas","07"

For an example of a map, let's take one from our national statistics institution INEGI: 
![nacionalestados_inegi](https://user-images.githubusercontent.com/24779456/42778880-2f19c110-8904-11e8-97db-3e5dc13d2b52.PNG)

And for an example of this grid, we can make a visualization of the 2018 Federal Election to the Senate. In each of the 32 Mexican states (formally, CDMX is not a state, but let's skeep that), parties present an ordered two candidates ticket. The first place ticket gets to send both its candidates to the Senate, this is known in Mexico as "Mayoría Relativa" (MR1/MR2 in the plot). The second place ticket only gets its first candidate elected as a "Primera Minoría" Senator (PM on the plot). Parties can form a coalition to present a ticket, but individual candidates must be asigned to a specific party, therefore we can see how Senators from each party were elected and with what share of votes. 

![ejemplo_geofacet_mx](https://user-images.githubusercontent.com/24779456/42778887-338dc782-8904-11e8-8c0c-3692429632ae.PNG)

Just for completeness, I will say that Mexico's Senate election is a mixed system with these 96 (64 MR + 32 PM) directly elected Senators and 32 Senators elected proportionally according to the national share of votes each party had. The code I used for this plot is [here](https://github.com/fazepher/mx_state_grid3)

I hope you find it nice to add to geofacet.

**Comment by stedy** [comment]
This issue addressed in [geofacet version 0.2.0](https://cran.r-project.org/web/packages/geofacet/index.html)
