### ISSUE TITLE
sg_district_grid1

### ISSUE THREAD

**Issue by Elenafuyi** [hafen/geofacet#138]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row,col,code,name
1,4,27,FAR NORTH
2,5,28,NORTH EAST
2,3,26,NORTH
2,2,25,FAR NORTH
3,1,24,FAR NORTH WEST
3,2,23,NORTH WEST
3,4,20,CENTRAL NORTH
3,6,19,NORTH EAST
3,7,18,FAR EAST
3,8,17,FAR EAST
4,2,21,CENTRAL WEST
4,3,11,CENTRAL
4,4,12,CENTRAL
4,5,13,CENTRAL EAST
4,6,14,CENTRAL EAST
4,8,16,UPPER EAST COAST
4,7,15,EAST COAST
5,1,22,FAR WEST
5,3,10,CENTRAL
5,4,9,CENTRAL
5,6,8,CENTRAL
5,5,7,CITY
6,6,1,CITY
6,3,5,SOUTH WEST
6,4,3,CENTRAL SOUTH
6,5,6,CITY
7,4,4,SOUTH
7,5,2,CITY
```

![map](http://www.propertyhub.com.sg/images/M_images/singapore_district_map.jpg)

District name see for here:http://www.propertyhub.com.sg/singapore-district-guide.html

This is the district code map and name for Singapore. Feel free to contact me:
Email: yi.fu.2017@mitb.smu.edu.sg
Call: +65 83365818

Thank you.

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
