### ISSUE TITLE
sg_PlanningArea_grid

### ISSUE THREAD

**Issue by Elenafuyi** [hafen/geofacet#140]
Grid data:

```
row,col,code,name
1,7,WD,WOODLANDS
1,8,SB,SEMBAWANG
1,9,SE,SIMPANG
1,10,SL,SELETAR
2,7,MD,MANDAI
2,8,YS,YISHUN
2,9,SE,SENGKANG
2,10,PG,PUNGGOL
3,4,CK,CHAO CHU KANG
3,5,SK,SUNGEI KADUT
3,6,BS,BISHAN
3,7,TP,TOA PAYOH
3,8,AM,ANG MO KIO
3,9,SG,SERANGOON
3,10,HG,HOUGANG
3,11,PL,PAYA LEBAR
3,12,PR,PASIR RIS
4,3,LK,LIM CHU KANG
4,4,TH,TENGAH
4,5,CC,CENTRAL WATER CATCHMENT
4,6,TL,TANGLIN
4,7,NT,NEWTON
4,8,RC,ROCHOR
4,9,KL,KALLANG
4,10,GL,GEYLANG
4,11,BD,BEDOK
4,12,TM,TAMPINES
4,13,CH,CHANGI
5,2,WC,WESTERN WATER CATCHMENT
5,3,JW,JURONG WEST
5,4,BK,BUKIT BATOK
5,5,BP,BUKIT PANJANG
5,6,NV,NOVENA
5,7,OR,ORCHARD
5,8,MU,MUSEUM
5,9,ME,MARINA EAST
5,10,MP,MARINE PARADE
6,1,TS,TUAS
6,2,PN,PIONEER
6,3,BL,BOON LAY
6,4,JE,JURONG EAST
6,5,BT,BUKIT TIMAH
6,6,RV,RIVER VALLY
6,7,DT,DOWNTOWN CORE
6,8,MS,MARINA SOUTH
7,4,CL,CLEMENTI
7,5,QT,QUEENSTOWN
7,6,SR,SINGAPORE RIVER
7,7,SV,STRAITS VIEW
8,6,BM,BUKIT MERAH
8,7,OT,OUTRAM
9,6,SI,SOUTHERN ISLANDS
```

The CODE and Planning area pls refer to this like from government page:
https://data.gov.sg/dataset/master-plan-2014-planning-area-boundary-web?view_id=248b1708-29c4-40bd-916f-7b0315f9f399&resource_id=f622fcd3-3478-4183-bda8-74779b35fe14

For a straight through version of planning area map can refer to this one.
![map](https://www.singstat.gov.sg/-/media/files/publications/population/population2015-map1.pdf)

Let me know what else I need to submit for creating Singapore Planning Area grid.
yi.fu.2017@mitb.smu.edu.sg  

+65 83365818

Thank you,
FU YI

**Comment by xang1234** [comment]
Hi Fu Yu,

Good effort. This will be useful. Just some points: 
- `RIVER VALLY` should be spelt `RIVER VALLEY`
- `CHAO CHU KANG` should be spelt `CHOA CHU KANG`
- There are 55 Planning Areas. `WESTERN ISLANDS`, `NORTH-EASTERN ISLANDS` and `CHANGI BAY` are left out. Of course, there's nothing much there but maybe they should be included for completeness

**Comment by Elenafuyi** [comment]
Hi David,

Thank you for letting me know the missing parts. I have uploaded a latest version of Singapore Planning Area on Github, 55 Planning areas in total.

Github link: Issue 145<https://github.com/hafen/geofacet/issues/145>

Let me know anything I can improve more.
Happy to contribute.


Best regards,
Fu Yi



________________________________

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
