### ISSUE TITLE
Geofacet grid for Fujian province of CHINA

### ISSUE THREAD

**Issue by nannanchen333** [hafen/geofacet#141]
The grid I built is for city/county level in Fujian province of China. 

Grid data:

```
area,row,col
Pucheng,1,4
Songxi,2,4
Chongan,2,3
Shouning,2,6
Zhenghe,3,5
Jian'ou,3,4
Jianyang,3,3
Guangze,3,2
Zherong,3,7
Fuding,3,8
Fu'an,4,7
Shunchang,4,3
Shaowu,5,2
Jiangle,5,3
Nanping,5,4
Pingnan,5,6
Zhouning,5,7
Jiaocheng,5,8
Xiapu,5,9
Taining,6,2
Sha,6,4
Youxi,6,5
Gutian,6,6
Luoyuan,6,8
Lianjiang,6,9
Minqing,7,6
Minhou,7,7
Fuzhou,7,8
Changle,7,9
Jianning,7,2
Sanyuan,7,4
Ninghua,8,1
Shanming,8,4
Yongtai,8,8
Fuqing,8,9
Mingxi,8,3
Putian County,9,8
Xianyou,9,7
Dehua,9,6
Datian,9,5
Yong'an,9,4
Qingliu,9,2
Yongchun,10,6
Hui'an,10,7
Putian,10,8
Changting,11,1
Luojiang,11,7
Nan'an,11,6
Anxi,11,5
Liancheng,11,3
Zhangping,12,4
Jinjiang,12,6
Shishi,12,7
Xiamen,13,7
Tong'an,13,6
Changtai,13,5
Hua'an,13,4
Shanghang,14,3
Wuping,14,2
Longhai,14,6
Yongding,15,3
Zhangzhou,15,4
Zhangpu,15,5
Nanjing,16,4
Pinghe,16,3
Dongshan,17,5
Zhao'an,17,4
```

**Comment by nannanchen333** [comment]
mygrid <- data.frame(
 name = c("Pucheng", "Songxi", "Chongan", "Shouning", "Zhenghe", "Jian'ou", "Jianyang", "Guangze", "Zherong", "Fuding", "Fu'an", "Shunchang", "Shaowu", "Jiangle", "Nanping", "Pingnan", "Zhouning", "Jiaocheng", "Xiapu", "Taining", "Sha", "Youxi", "Gutian", "Luoyuan", "Lianjiang", "Minqing", "Minhou", "Fuzhou", "Changle", "Jianning", "Sanyuan", "Ninghua", "Shanming", "Yongtai", "Fuqing", "Mingxi", "Putian County", "Xianyou", "Dehua", "Datian", "Yong'an", "Qingliu", "Yongchun", "Hui'an", "Putian", "Changting", "Luojiang", "Nan'an", "Anxi", "Liancheng", "Zhangping", "Jinjiang", "Shishi", "Xiamen", "Tong'an", "Changtai", "Hua'an", "Shanghang", "Wuping", "Longhai", "Yongding", "Zhangzhou", "Zhangpu", "Nanjing", "Pinghe", "Dongshan", "Zhao'an"),
 code = c("Pucheng", "Songxi", "Chongan", "Shouning", "Zhenghe", "Jian'ou", "Jianyang", "Guangze", "Zherong", "Fuding", "Fu'an", "Shunchang", "Shaowu", "Jiangle", "Nanping", "Pingnan", "Zhouning", "Jiaocheng", "Xiapu", "Taining", "Sha", "Youxi", "Gutian", "Luoyuan", "Lianjiang", "Minqing", "Minhou", "Fuzhou", "Changle", "Jianning", "Sanyuan", "Ninghua", "Shanming", "Yongtai", "Fuqing", "Mingxi", "Putian County", "Xianyou", "Dehua", "Datian", "Yong'an", "Qingliu", "Yongchun", "Hui'an", "Putian", "Changting", "Luojiang", "Nan'an", "Anxi", "Liancheng", "Zhangping", "Jinjiang", "Shishi", "Xiamen", "Tong'an", "Changtai", "Hua'an", "Shanghang", "Wuping", "Longhai", "Yongding", "Zhangzhou", "Zhangpu", "Nanjing", "Pinghe", "Dongshan", "Zhao'an"),
  row = c(1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 17, 17),
  col = c(4, 4, 3, 6, 5, 4, 3, 2, 7, 8, 7, 3, 2, 3, 4, 6, 7, 8, 9, 2, 4, 5, 6, 8, 9, 6, 7, 8, 9, 2, 4, 1, 4, 8, 9, 3, 8, 7, 6, 5, 4, 2, 6, 7, 8, 1, 7, 6, 5, 3, 4, 6, 7, 7, 6, 5, 4, 3, 2, 6, 3, 4, 5, 4, 3, 5, 4),
  stringsAsFactors = FALSE
)
geofacet::grid_preview(mygrid)

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/54298318-c2035800-4575-11e9-8d68-868cc76315df.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
