### ISSUE TITLE
capcog_counties

### ISSUE THREAD

**Issue by mth444** [hafen/geofacet#146]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
County,row,col
Burnet,1,2
Llano,1,1
Williamson,1,3
Lee,1,4
Travis,2,3
Bastrop,2,4
Blanco,2,2
Fayette,3,5
Hays,3,3
Caldwell,3,4
```

**Comment by hafen** [comment]
Can you provide a map for reference and describe what this is a grid of?

**Comment by mth444** [comment]
This is a grid of a 10 county planning region around Austin, Texas. Attached is a PDF map.

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/2/23/CAPCOG.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by mth444** [comment]
Thanks!
