### ISSUE TITLE
Typos in "de_states_grid1"

### ISSUE THREAD

**Issue by sebastiansauer** [hafen/geofacet#151]
wrong: "Sachen"; correct: "Sachsen"
wrong: "Nordrhein-Westphalen"; correct: "Nordrhein-Westfalen"

**Comment by sebastiansauer** [comment]
Sorry, I meant:

wrong: "Niedersachen", correct: "Niedersachsen"
wrong: "Nordrhein-Westphalen"; correct: "Nordrhein-Westfalen"

**Comment by stedy** [comment]
This was addressed in [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
