### ISSUE TITLE
new grid: 'ch_bj_grid1'

### ISSUE THREAD

**Issue by shiedelweiss** [hafen/geofacet#156]
Beijing district grid

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","name","code"
1,2,"Yanqing","YQ"
1,3,"Huairou","HR"
1,4,"Miyun","MY"
1,5,"Pinggu","PG"
2,3,"Changping","CP"
2,4,"Shunyi","SY"
3,2,"Haidian","HD"
3,4,"Dongcheng","DC"
3,5,"Chaoyang","CY"
3,3,"Xicheng","XC"
4,1,"Mentougou","MTG"
4,2,"Shijingshan","SJS"
4,4,"Chongwen","CW"
4,5,"Tongzhou","TZ"
4,3,"Xuanwu","XW"
5,1,"Fangshan","FS"
5,4,"Daxing","DX"
5,3,"Fengtai","FT"
```

**Comment by stedy** [comment]
Addressed in https://github.com/hafen/geofacet/issues/157
