### ISSUE TITLE
new grid: 'sa_prov_grid2'

### ISSUE THREAD

**Issue by kamermanpr** [hafen/geofacet#159]
Alternative grid of South Africa's 9 Provinces

# Image
<img width="828" alt="screenshot 2019-03-03 at 16 37 58" src="https://user-images.githubusercontent.com/10417813/53696727-d6f02680-3dd2-11e9-9382-6653f5abe185.png">

# Sample data and code
[geofacetSA.txt](https://github.com/hafen/geofacet/files/2923234/geofacetSA.txt)

Grid data:

```
"row","col","code_iso","code_abb","name","name_af"
4,1,"WC","WC","Western Cape","Wes-Kaap"
4,2,"EC","EC","Eastern Cape","Oos-Kaap"
3,1,"NC","NC","Northern Cape","Noord-Kaap"
2,3,"GT","GP","Gauteng","Gauteng"
3,3,"NL","KZN","KwaZulu-Natal","KwaZulu-Natal"
2,4,"MP","MP","Mpumalanga","Mpumalanga"
1,3,"LP","LP","Limpopo","Limpopo"
2,2,"NW","NW","North West","Noordwes"
3,2,"FS","FS","Free State","Vrystaat"
```

**Comment by stedy** [comment]
![](https://www.southafrica.to/provinces/RSA_by_provinces.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
