### ISSUE TITLE
new grid: very rough approximation for Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [hafen/geofacet#162]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
ubigeo_inei,departamento,ubigeo_reniec,row,col
24,Tumbes,23,2,1
16,Loreto,15,1,4
06,Cajamarca,06,2,2
01,Amazonas,01,2,3
25,Ucayali,25,2,4
20,Piura,19,3,1
14,Lambayeque,13,3,2
22,San Martín,21,3,3
08,Cusco,07,4,4
10,Huánuco,09,4,3
13,La Libertad,12,4,2
17,Madre de Dios,16,5,5
09,Huancavelica,08,5,4
03,Apurímac,03,5,4
02,Ancash,02,5,2
19,Pasco,18,5,3
21,Puno,20,6,5
12,Junín,11,6,3
15,Lima,14,6,2
05,Ayacucho,05,6,4
07,Callao,24,7,1
11,Ica,10,7,3
04,Arequipa,04,7,4
18,Moquegua,17,7,5
23,Tacna,22,8,5
```

![map](https://imagenestotales.com/wp-content/uploads/2018/04/Mapa-politico-del-Peru-2-768x936.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
