### ISSUE TITLE
afghanistan_provinces

### ISSUE THREAD

**Issue by jrennyb** [hafen/geofacet#164]
Provinces of Afghanistan
Grid data:

```
Province,row,col
Faryab,1,3
Jowzjan,1,4
Balkh,1,5
Kunduz,1,6
Takhar,1,7
Badakhshan,1,8
Badghis,2,3
Samangan,2,5
Sar-e Pol,2,4
Baghlan,2,6
Nuristan,2,8
Panjshir,2,7
Herat,3,1
Ghor,3,2
Bamyan,3,4
Parwan,3,6
Kapisa,3,7
Laghman,3,8
Kunar,3,9
Daykundi,3,3
Farah,4,2
Maidan Wardak,3,5
Ghazni,4,4
Kabul,4,6
Logar,4,7
Nangarhar,4,8
Khost,5,8
Paktia,5,7
Urozgan,5,4
Zabul,5,5
Paktika,6,7
Kandahar,6,5
Helmand,6,4
Nimruz,6,3
```

![map](https://en.wikipedia.org/wiki/Provinces_of_Afghanistan#/media/File:Afghanistan_provinces_named.png)

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/4/44/Afghanistan_provinces_numbered.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
