### ISSUE TITLE
new grid: 'Taiwan'

### ISSUE THREAD

**Issue by csh484912274** [hafen/geofacet#166]
An awesome grid...

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
1,3,"TP","Taipei City"
1,4,"NTP","New Taipei City"
1,5,"KL","Keelung City"
2,1,"LC","Lienchiang"
2,4,"HC","Hsinchu"
2,5,"HCC","Hsinchu City"
2,3,"TY","Taoyuan City"
2,6,"ML","Miaoli"
3,1,"KM","Kinmen"
3,3,"TC","Taichung City"
3,4,"CH","Changhua"
3,5,"NT","Nantou"
4,1,"PH","Penghu"
4,3,"YUL","Yunlin"
4,4,"CY","Chiayi"
4,5,"CYC","Chiayi City"
4,6,"TN","Tainan City"
5,3,"KH","Kaohsiung"
5,4,"PT","Pingtung"
6,4,"HL","Hualien"
6,5,"TT","Taitung"
6,3,"YL","Yilan"
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Taiwan_ROC_political_divisions_labeled.svg/1200px-Taiwan_ROC_political_divisions_labeled.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2.0](https://cran.r-project.org/web/packages/geofacet/index.html)
