### ISSUE TITLE
us_hhsregiongrid

### ISSUE THREAD

**Issue by akitepowell** [hafen/geofacet#168]
These grid approximates the U.S. Health and Human Services Region map. For more info see: https://www.hhs.gov/about/agencies/iea/regional-offices/index.html

Grid data:

```
code,name,row,col
region1,HHS Region 1,1,5
region10,HHS Region 10,1,1
region8,HHS Region 8,1,2
region2,HHS Region 2,1,4
region5,HHS Region 5,2,3
region9,HHS Region 9,2,1
region7,HHS Region 7,2,2
region3,HHS Region 3,2,4
region6,HHS Region 6,3,2
region4,HHS Region 4,3,4
```

**Comment by stedy** [comment]
![](https://www.hhs.gov/sites/default/files/iea/images/regionsmap.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
