### ISSUE TITLE
new grid: 'bulgaria_regions_grid'

### ISSUE THREAD

**Issue by savinastoitsova** [hafen/geofacet#169]
Geofacet grid of Bulgarian regions

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a 
![Bulgaria_Administrative_Provinces](https://user-images.githubusercontent.com/37689546/59753121-26783680-928c-11e9-9d85-205d32e325ea.png)
data set and sample code, that would be great but is not required.]]

Grid data:

```
"code","name","row","col"
1,"Vidin",1,1
2," Pleven",1,3
3," Dobrich",1,6
4," Russe",1,4
5," Silistra",1,5
6," Shumen",2,5
7," Vratsa",2,2
8," Veliko Tarnovo",2,3
9," Montana",2,1
10,"  Razgrad",2,4
11," Varna",3,5
12," Targovishte",3,4
13," Gabrovo",3,3
14," Sofia",3,1
15," Lovech",3,2
16," Sofia-city",4,2
17," Burgas",4,5
18," Stara Zagora",4,3
19," Pernik",4,1
20," Sliven",4,4
21," Yambol",5,5
22," Pazardzhik",5,2
23," Haskovo",5,4
24," Plovdiv",5,3
25," Kiustendil",5,1
26," Kardzhali",6,4
27," Smolyan",6,3
28," Blagoevgrad",6,2
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/8/86/Regions_of_Bulgaria_Map.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
