### ISSUE TITLE
new grid: oregon_county_grid1

### ISSUE THREAD

**Issue by aosmith16** [hafen/geofacet#17]
Oregon counties

Grid data:

```
name,code,row,col
Clatsop,CL,1,1
Columbia,CO,1,2
Multnomah,ML,2,3
Tillamook,TL,2,1
Washington,WA,2,2
HoodRiver,HR,2,4
Sherman,SH,2,5
Gilliam,GL,2,6
Morrow,MR,2,7
Wallowa,WL,2,8
Umatilla,UM,3,8
Wasco,WS,3,4
Clackamas,CK,3,3
Yamhill,YM,3,2
Union,UN,3,7
Lincoln,LC,4,1
Baker,BK,4,8
Grant,GR,4,7
Wheeler,WH,4,6
Jefferson,JE,4,4
Polk,PK,4,2
Marion,MN,4,3
Benton,BE,5,2
Linn,LN,5,3
Lane,LA,5,1
Crook,CR,6,5
Deschutes,DC,6,4
Coos,CS,6,1
Douglas,DO,6,2
Curry,CU,7,1
Josephine,JO,7,2
Jackson,JC,7,3
Klamath,KL,7,4
Lake,LK,7,5
Harney,HA,7,6
Malheur,MH,7,8
```

![oregon-map-blue](https://user-images.githubusercontent.com/11638312/27445795-01b77804-5730-11e7-919b-36cde8027706.jpg)

**Comment by hafen** [comment]
Nice! I did one for WA a few days ago too so we have the Pacific Northwest covered. I'll get this and the other new ones merged in the next few days.

**Comment by hafen** [comment]
Nice! I did one for WA a few days ago too so we have the Pacific Northwest covered. I'll get this and the other new ones merged in the next few days.

**Comment by hafen** [comment]
Added. Thanks!
