### ISSUE TITLE
new grid: 'mexicocity_boroughs'

### ISSUE THREAD

**Issue by Ivangea** [hafen/geofacet#170]
This grid is a spatial representation of the 16 Mexico City boroughs

https://es.wikipedia.org/wiki/Portal:Ciudad_de_M%C3%A9xico/Delegaciones

Grid data:

```
"row","col","name","code"
1,3,"Azcapotzalco","Azcapotzalco"
4,3,"Coyoacán","Coyoacán"
3,1,"Cuajimalpa de Morelos","Cuajimalpa de Morelos"
1,4,"Gustavo A. Madero","Gustavo A. Madero"
3,4,"Iztacalco","Iztacalco"
3,5,"Iztapalapa","Iztapalapa"
4,2,"La Magdalena Contreras","La Magdalena Contreras"
5,4,"Milpa Alta","Milpa Alta"
3,2,"Álvaro Obregón","Álvaro Obregón"
4,4,"Tláhuac","Tláhuac"
5,2,"Tlalpan","Tlalpan"
5,3,"Xochimilco","Xochimilco"
3,3,"Benito Juárez","Benito Juárez"
2,3,"Cuauhtémoc","Cuauhtémoc"
2,2,"Miguel Hidalgo","Miguel Hidalgo"
2,4,"Venustiano Carranza","Venustiano Carranza"
```

**Comment by stedy** [comment]
![Districts of Mexico City, Mexico](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/MX-DF-Divisi%C3%B3n_pol%C3%ADtica.svg/800px-MX-DF-Divisi%C3%B3n_pol%C3%ADtica.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
