### ISSUE TITLE
new grid: provinces and territories of Canada

### ISSUE THREAD

**Issue by michael-chong** [hafen/geofacet#174]
Grid data:

```
row,col,code,name
1,1,YT,Yukon
1,2,NT,Northwest Territories
1,4,NU,Nunavut
1,6,NL,Newfoundland and Labrador
1,7,PE,Prince Edward Island
2,1,BC,British Columbia
2,2,AB,Alberta
2,3,SK,Saskatchewan
2,4,MB,Manitoba
2,5,ON,Ontario
2,6,QC,Quebec
2,7,NB,New Brunswick
2,8,NS,Nova Scotia
```

![map](https://www.nrcan.gc.ca/sites/www.nrcan.gc.ca/files/energy/images/erf-cfe/CANADA.png)

**Comment by stedy** [comment]
![Provinces of Canada](https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Political_map_of_Canada.png/800px-Political_map_of_Canada.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
