### ISSUE TITLE
"Empty states" when combining with other ggplots

### ISSUE THREAD

**Issue by Z3tt** [hafen/geofacet#175]
Hi, thanks for this wonderful package! Today, when trying to combine a geofacet with another ggplot, I found out that none of my usual ways to do so (patchwork, cowplot, gridExtra didnit lead to the expected outcome - always facets for "empty states" are drawn:

``` r
library(ggplot2)
#> Warning: Paket 'ggplot2' wurde unter R Version 3.5.3 erstellt
library(geofacet)
#> Warning: Paket 'geofacet' wurde unter R Version 3.5.3 erstellt

theme_set(theme_bw())

(geofacet <- 
  ggplot(state_ranks,
         aes(variable, rank, fill = variable)) +
    geom_col() +
    coord_flip() +
    facet_geo(~ state) +
    guides(fill = F))
```

![](https://i.imgur.com/anyxMC9.png)

``` r

(dotplot <- 
    ggplot(state_ranks, 
           aes(state, rank, color = variable)) +
      geom_point() +
      coord_flip())
```

![](https://i.imgur.com/XwYfo9r.png)

``` r

library(patchwork)
geofacet + dotplot + plot_layout(nrow = 1)
```

![](https://i.imgur.com/b5T4go7.png)

``` r

library(cowplot)
#> Warning: Paket 'cowplot' wurde unter R Version 3.5.3 erstellt
#> 
#> ********************************************************
#> Note: As of version 1.0.0, cowplot does not change the
#>   default ggplot2 theme anymore. To recover the previous
#>   behavior, execute:
#>   theme_set(theme_cowplot())
#> ********************************************************
plot_grid(geofacet, dotplot, nrow = 1)
```

![](https://i.imgur.com/H5vhq12.png)

``` r

library(gridExtra)
grid.arrange(geofacet, dotplot, nrow = 1)
```

![](https://i.imgur.com/eClzk39.png)

<sup>Created on 2019-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was wondering if you know a workaround and was surprised that I couldn't find any previous issue on this (sorry if I missed it!).

Best,
Cédric

**Comment by hafen** [comment]
Thanks for the reproducible example. Geofacet does some manipulation to the underlying ggplot object that these other grid arrangement packages aren't aware of.

I just added a convenience function to the package (not on CRAN, but in the master branch), `get_geofacet_grob()`, that performs these manipulations so that you can then take the resulting object and use it with these other packages.

For example

```r
library(ggplot2)

theme_set(theme_bw())

(geofacet <- 
  ggplot(state_ranks,
         aes(variable, rank, fill = variable)) +
    geom_col() +
    coord_flip() +
    facet_geo(~ state) +
    guides(fill = F))

(dotplot <- 
    ggplot(state_ranks, 
           aes(state, rank, color = variable)) +
      geom_point() +
      coord_flip())

geofacet_grob <- get_geofacet_grob(geofacet)

library(cowplot)
plot_grid(geofacet_grob, dotplot, nrow = 1)
```

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/1275592/66007668-2c271000-e468-11e9-8a84-ce6b6f857484.png">

**Comment by Z3tt** [comment]
Perfect, this was what I was looking for! Thanks for adding the function in no time, it will be very useful.
