### ISSUE TITLE
Dutch Provinces

### ISSUE THREAD

**Issue by ruditurksema** [hafen/geofacet#178]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row,col,code,name
1,2,FR,Friesland
1,3,GR,Groningen
2,1,NH,Noord-Holland
2,3,DR,Drenthe
2,2,FL,Flevoland
3,1,ZH,Zuid-Holland
3,3,OV,Overijssel
3,2,UT,Utrecht
4,3,GE,Gelderland
4,2,NB,Noord-Brabant
4,1,ZE,Zeeland
5,3,LI,Limburg
```

![map](http://1.bp.blogspot.com/-DztsF0ghmtE/T3r-Y1M-VPI/AAAAAAAAAss/-hYbi2iORz8/s1600/usa-map-region.gif)

**Comment by stedy** [comment]
![Image of Dutch Provinces](https://upload.wikimedia.org/wikipedia/commons/c/cc/Map_provinces_Netherlands-en.svg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2.0](https://cran.r-project.org/web/packages/geofacet/index.html)
