### ISSUE TITLE
new grid

### ISSUE THREAD

**Issue by Ricardo95RM** [hafen/geofacet#179]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
cod_provincias,PROVINCIAS,row,col
04,CARCHI,1,4
08,ESMERALDAS,2,2
10,IMBABURA,2,4
21,SUCUMBIOS,2,6
17,PICHINCHA,3,4
22,ORELLANA,3,7
23,SANTO DOMINGO DE LOS TSACHILAS,3,3
15,NAPO,3,5
13,MANABI,3,2
05,COTOPAXI,4,4
16,PASTAZA,4,7
12,LOS RIOS,4,3
24,SANTA ELENA,5,1
09,GUAYAS,5,2
18,TUNGURAHUA,5,4
02,BOLIVAR,5,3
14,MORONA SANTIAGO,6,6
06,CHIMBORAZO,6,5
07,EL ORO,7,2
03,CAÑAR,7,4
01,AZUAY,7,3
19,ZAMORA CHINCHIPE,7,5
11,LOJA,8,3
```

![map](https://ecuadornoticias.com/wp-content/uploads/2017/04/provincias-ecuador.jpg)

**Comment by stedy** [comment]
Addressed in https://github.com/hafen/geofacet/issues/180
