### ISSUE TITLE
mm_state_grid1

### ISSUE THREAD

**Issue by htinkyawaye** [hafen/geofacet#185]
[[Note: This is top-level Myanmar state/region grid. This has to be complimented with subdivisions and capital Nay Pyi Taw in a separate grid.]]

Grid data:

```
code,name,row,col
MM-11,Kachin,1,3
MM-14,Chin,2,2
MM-01,Sagaing,2,3
MM-03,Magway,3,2
MM-04,Mandalay,3,3
MM-16,Rakhine,3,1
MM-17,Shan,3,4
MM-12,Kayah,4,3
MM-02,Bago,4,2
MM-07,Ayeyarwady,4,1
MM-13,Kayin,5,3
MM-06,Yangon,5,2
MM-15,Mon,6,3
MM-05,Tanintharyi,7,3
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Burma_administrative_divisions.svg/300px-Burma_administrative_divisions.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
