### ISSUE TITLE
US_state_dc_grid1

### ISSUE THREAD

**Issue by krothkin** [hafen/geofacet#186]
A grid of the 50 US states plus DC. If desired, add Puerto Rico (PR) at row=9, col = 12. 
Note AK is at the top and HI is at the bottom

Grid data:
mygrid <- data.frame(
 row=c(1,1,2,2,3,3,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,9,9,9),
col=c(1,12,10,11,9,10,1,2,3,4,5,6,7,8,9,10,11,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,2,3,4,5,6,7,8,4,5,6,7,8,1,4,8),
code=c('AK','ME','VT','NH','NY','MA','WA','ID','MT','ND','MN','WI','MI','OH','NJ','CT','RI','OR','UT','WY','SD','IA','IL','IN','PA','MD','DC','CA','NV','CO','NE','MO','KY','WV','VA','DE','AZ','NM','KS','AR','TN','AL','NC','OK','LA','MS','GA','SC','HI','TX','FL'),
  stringsAsFactors = FALSE
)

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Map_of_USA_PR.svg/1200px-Map_of_USA_PR.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
