### ISSUE TITLE
us_stateDC_grid2

### ISSUE THREAD

**Issue by krothkin** [hafen/geofacet#187]
Another, more compact US map including DC. This is only 8 rows high

Grid data:
--
row=c(1,1,1,1,2,2,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,7,7,7,7,7,8,8,8),
col=c(1,10,11,12,9,10,1,2,3,4,5,6,7,8,9,10,11,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,2,3,4,5,6,7,8,4,5,6,7,8,1,4,8),
code=c('AK','VT','NH','ME','NY','MA','WA','ID','MT','ND','MN','WI','MI','OH','NJ','CT','RI','OR','UT','WY','SD','IA','IL','IN','PA','MD','DC','CA','NV','CO','NE','MO','KY','WV','VA','DE','AZ','NM','KS','AR','TN','AL','NC','OK','LA','MS','GA','SC','HI','TX','FL'),

 stringsAsFactors = FALSE

```

```

**Comment by stedy** [comment]
![](https://camo.githubusercontent.com/5038126fbe0052e7d42602dc6856aedc7822f639/687474703a2f2f6269742e6c792f75732d67726964)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
