### ISSUE TITLE
new grid: 'Salta Province - Argentina'

### ISSUE THREAD

**Issue by tartagalensis** [hafen/geofacet#190]
Province of Salta (Argentina) and its departments

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"name","code","row","col"
"S. VICTORIA","SANTA VICTORIA",1,5
"IRUYA","IRUYA",2,5
"SAN MARTIN","SAN MARTIN",2,6
"ORAN","ORAN",3,6
"LA POMA","LA POMA",3,2
"GÜEMES","GENERAL GÜEMES",3,5
"RIVADAVIA","RIVADAVIA",2,7
"LA CALDERA","LA CALDERA",3,4
"ROS. LERMA","ROSARIO DE LERMA",4,3
"LOS ANDES","LOS ANDES",4,2
"CAPITAL","CAPITAL",4,5
"ANTA","ANTA",4,6
"CERRILLOS","CERRILLOS",4,4
"CACHI","CACHI",5,3
"METAN","METAN",5,5
"CHICOANA","CHICOANA",5,4
"MOLINOS","MOLINOS",6,2
"SAN CARLOS","SAN CARLOS",6,3
"ROS. FRONT.","ROS. DE LA FRONTERA",6,6
"LA VIÑA","LA VIÑA",6,4
"GUACHIPAS","GUACHIPAS",6,5
"LA CAND.","LA CANDELARIA",7,5
"CAFAYATE","CAFAYATE",7,4
```

**Comment by stedy** [comment]
[](https://incluirsaludsalta.org.ar/wp-content/uploads/2017/06/mapa-salta.gif)

**Comment by stedy** [comment]
![](https://www.ametsalta.com.ar/web/images/aniversarios/24404462.jpg)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
