### ISSUE TITLE
California Counties

### ISSUE THREAD

**Issue by MartinLe5** [hafen/geofacet#197]
Grid data:

```
County,row,col
Del Norte,1,2
Modoc,1,5
Siskiyou,1,4
Humboldt,2,2
Lassen,2,5
Shasta,2,4
Trinity,2,3
Mendocino,3,2
Plumas,3,4
Tehama,3,3
Butte,4,4
Glenn,4,3
Lake,4,2
Sierra,4,5
Colusa,5,3
Nevada,5,6
Sutter,5,4
Yuba,5,5
El Dorado,6,6
Napa,6,2
Placer,6,5
Sacramento,6,4
Sonoma,6,1
Yolo,6,3
Alpine,7,5
Amador,7,4
Marin,7,2
Solano,7,3
Calaveras,8,5
Contra Costa,8,3
San Francisco,8,2
San Joaquin,8,4
Alameda,9,3
Mono,9,6
San Mateo,9,2
Stanislaus,9,4
Tuolumne,9,5
Madera,10,6
Mariposa,10,5
Merced,10,4
Santa Clara,10,3
Santa Cruz,10,2
Fresno,11,4
Inyo,11,5
Monterey,11,2
San Benito,11,3
Kings,12,3
Tulare,12,4
San Luis Obispo,13,2
Kern,13,3
San Bernardino,13,4
Santa Barbara,14,2
Riverside,15,4
Ventura,14,3
Los Angeles,15,3
Imperial,16,5
San Diego,16,4
Orange,16,3
```

![map](https://en.wikipedia.org/wiki/List_of_counties_in_California#/media/File:California_Locator_Map.PNG)

**Comment by MartinLe5** [comment]
Middle and Southern California are a bit weird, since there's a fair number of states in the middle that are adjacent to more than 4 counties, and very large counties in the SoCal that don't really line up nicely into square bins.

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/California_county_map_%28labeled%29.svg/800px-California_county_map_%28labeled%29.svg.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
