### ISSUE TITLE
Grid for Non-EU or US states

### ISSUE THREAD

**Issue by jasonjb82** [hafen/geofacet#2]
Is there a possibility to include grids for South East Asian countries? What would be required to create such a grid.

Thanks.

**Comment by hafen** [comment]
Right now grids must be created manually and their creation is somewhat objective. I'd love to figure out an automatic grid algorithm but it will be difficult (I'll write about this soon). To create a grid, you need a data frame with variables `code`, `name`, `row`, `col`. The `row` and `col` variables are expected to be positive integers indicating the placement of the geographic entity going from left-to-right, top-to-bottom. Then you can pass this in as the `grid` argument to `facet_geo()`.

If your grid is one that you think will be of general benefit to others, you can pass your grid data frame into a helper function `submit_grid()` that will open up an issue for you here and make it easy for me to place in the package. One was just submitted here https://github.com/hafen/geofacet/issues/3 that I'm going to merge.

If you'd like to take a stab at creating a grid for these regions and want to submit it to the package, that would be great!

**Comment by jasonjb82** [comment]
Thanks for the very clear and detailed explanation. I will be happy to have a take a stab at creating a grid and submit it!

**Comment by happyshows** [comment]
I think the difficulty in mapping is because the gap in actual country size and virtual country size. Maybe figure a way to cluster/group the smaller countries into bucket when compared with larger countries and let user to drill down on the bucket. But not sure if this is possible without shiny.

**Comment by hafen** [comment]
@jasonjb82 it is now much easier to create a grid. I went ahead and took a try at this one. Please visit [here](https://hafen.github.io/grid-designer/#data=name%2Ccode%2Crow%2Ccol%0ALaos%2CLA%2C1%2C2%0AMyanmar%2CMM%2C1%2C1%0AEast%20Timor%2CTL%2C4%2C5%0AVietnam%2CVN%2C2%2C3%0AThailand%2CTH%2C2%2C1%0ACambodia%2CKH%2C2%2C2%0APhilippines%2CPH%2C2%2C5%0ABrunei%2CBN%2C3%2C4%0AMalaysia%2CMY%2C3%2C1%0AIndonesia%2CID%2C4%2C4%0ASingapore%2CSG%2C4%2C2&img=https%3A%2F%2Fvignette2.wikia.nocookie.net%2Futau%2Fimages%2F8%2F82%2FSoutheast_asia.jpg%2Frevision%2Flatest%3Fcb%3D20110120041804) and you can edit the grid if you don't think it's quite right. Screenshot below:

<img width="1332" alt="screen shot 2017-06-20 at 12 27 14 pm" src="https://user-images.githubusercontent.com/1275592/27351991-0340b5f0-55b4-11e7-8f20-5d68a923744a.png">

**Comment by jasonjb82** [comment]
@hafen Thanks for a lot for this. I have just made some minor changes for Indonesia and East Timor and submitted the grid.
