### ISSUE TITLE
Error: The given dimensions cannot hold all panels. Please increase `ncol` or `nrow`

### ISSUE THREAD

**Issue by gruggeri** [hafen/geofacet#202]
Hello,

When I try to use 

```
   + facet_geo(~ code, grid = "ch_cantons_grid2",
                       scales = "free")
```

I receive the following error

```
Error: The given dimensions cannot hold all panels. Please increase `ncol` or `nrow`
```

How could I be able to print the plot? I looks like R studio thinks the whole plot is too big!

Giulia

**Comment by hafen** [comment]
Can you provide a reproducible example and your session information?

**Comment by gruggeri** [comment]
Ah yeah sorry, I was panicking... anyway a good old restart of Rstudio solved the issue... so I am going to close the issue if it's okay for you

**Comment by gruggeri** [comment]
or you may delete actually. Sorry for this...

**Comment by hafen** [comment]
That's interesting - glad it's working now!
