### ISSUE TITLE
new grid: 'sri_lanka_districts'

### ISSUE THREAD

**Issue by thiyangt** [hafen/geofacet#205]
Modified us_state_grid1 to include districts in Sri Lanka

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
8,1,"COL","Alabama"
7,1,"GAM","Alaska"
9,1,"KAL","Arizona"
7,3,"KAN","Arkansas"
6,3,"MAT","California"
8,3,"NE","Colorado"
10,2,"GAL","Connecticut"
10,4,"HAM","Delaware"
10,3,"MATARA","Florida"
1,3,"JAF","Georgia"
2,3,"KIL","Hawaii"
4,2,"MAN","Idaho"
4,3,"VAV","Illinois"
3,3,"MUL","Indiana"
5,5,"BAT","Iowa"
7,6,"AMP","Kansas"
4,4,"TRIN","Kentucky"
6,2,"KURU","Louisiana"
5,1,"PUT","Maine"
5,3,"ANU","Maryland"
5,4,"POLO","Massachusetts"
7,4,"BAD","Michigan"
7,5,"MON","Minnesota"
9,2,"RAT","Mississippi"
7,2,"KAG","Missouri"
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Districts_of_Sri_Lanka.png/1200px-Districts_of_Sri_Lanka.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
