### ISSUE TITLE
new grid: Sweden

### ISSUE THREAD

**Issue by duleise** [hafen/geofacet#22]
```
row,col,code,name
1,3,BD,Norrbotten
2,3,AC,Västerbotten
3,3,Y,Västernorrland
3,2,Z,Jämtland
4,2,W,Dalarna
4,3,X,Gävleborg
5,4,C,Uppsala
5,2,S,Värmland
5,3,U,Västmanland
6,4,AB,Stockholm
6,3,D,Södermanland
6,2,T,Örebro
7,3,E,Östergötland
7,2,O,Västra Götaland
8,2,F,Jönköping
8,3,H,Kalmar
8,5,I,Gotland
9,2,G,Kronoberg
9,1,N,Halland
10,2,K,Blekinge
10,1,M,Skåne
```

source: https://sv.wikipedia.org/wiki/Sveriges_län

**Comment by duleise** [comment]
it may cause a warning without this
`mygrid$code <- as.character(mygrid$code)`

**Comment by hafen** [comment]
Added. Thanks! Can you test it out now from the package to make sure the warning doesn't come up? It should be available as "se_counties_grid1" (if you don't update the package, it should be able to find it online but if you do update the package from GitHub, it's built-in).

**Comment by duleise** [comment]
Works smoothly as silk. Thanks.
