### ISSUE TITLE
new grid: 'india_with_uts'

### ISSUE THREAD

**Issue by dnyansagar** [hafen/geofacet#225]
Indian states with Union Territories

[[ ![image](https://user-images.githubusercontent.com/29943634/80574618-7a9e8c00-8a02-11ea-8387-1056410cb54b.png)
![image](https://user-images.githubusercontent.com/29943634/80574666-9013b600-8a02-11ea-804a-62f1a9547035.png)
Earlier I used india_grid2 from your collection but it excludes union territories. Therefore I created this grid. I have used this grid to map corona data on Indian states and union territories. Link to my GitHub repository is https://github.com/dnyansagar/DataScience ]]

Grid data:

```
"row","col","code","name"
1,3,"JK","Jammu and Kashmir"
2,8,"AR","Arunachal Pradesh"
2,3,"HP","Himachal Pradesh"
2,2,"PB","Punjab"
2,4,"UK","Uttarakhand"
3,7,"AS","Assam"
3,5,"BR","Bihar"
3,3,"HR","Haryana"
3,8,"NL","Nagaland"
3,2,"RJ","Rajasthan"
3,6,"SK","Sikkim"
3,4,"UP","Uttar Pradesh"
4,4,"CG","Chhattisgarh"
4,1,"GJ","Gujarat"
4,3,"JH","Jharkhand"
4,2,"MP","Madhya Pradesh"
4,8,"MN","Manipur"
4,7,"ML","Meghalaya"
4,5,"WB","West Bengal"
5,2,"MH","Maharashtra"
5,8,"MZ","Mizoram"
5,4,"OD","Odisha"
5,3,"TS","Telangana"
5,7,"TR","Tripura"
6,4,"AP","Andhra Pradesh"
6,2,"GA","Goa"
6,3,"KA","Karnataka"
7,3,"KL","Kerala"
7,4,"TN","Tamil Nadu"
9,1,"AN","Andaman and Nicobar Islands"
9,2,"CH","Chandigarh"
9,3,"DD","Dadra and Nagar Haveli and Daman and Diu"
9,4,"DL","Delhi"
9,5,"LA","Ladakh"
9,6,"LD","Lakshadweep"
9,7,"PY","Puducherry"
```

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
