### ISSUE TITLE
new grid: 'AUT_states_grid'

### ISSUE THREAD

**Issue by werkstattcodes** [hafen/geofacet#226]
Grid for the location of Austria's nine federal states. Codes are ISO-3166-2 codes.

![Austria_mobility_reports](https://user-images.githubusercontent.com/9595585/80590524-4d5ed780-8a1c-11ea-805f-091486a55f66.png)
![The_States_of_Austria_Numbered svg](https://user-images.githubusercontent.com/9595585/80590528-4e900480-8a1c-11ea-9bf0-151cce354249.png)

Grid data:

```
"code","name_en","row","col"
"4","Upper Austria",1,3
"3","Lower Austria",1,4
"9","Vienna",1,5
"8","Vorarlberg",2,1
"7","Tyrol",2,2
"5","Salzburg",2,3
"6","Styria",2,4
"1","Burgenland",2,5
"2","Carinthia",3,4
```

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
