### ISSUE TITLE
geofacet_france_dep

### ISSUE THREAD

**Issue by jerbou** [hafen/geofacet#229]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
dep,col,row
80,5,1
60,6,1
02,7,1
76,4,2
95,5,2
93,6,2
51,7,2
08,8,2
57,9,2
14,3,3
27,4,3
92,5,3
75,6,3
77,7,3
53,8,3
54,9,3
67,10,3
56,1,4
35,2,4
53,3,4
72,4,4
28,5,4
91,6,4
10,7,4
52,8,4
88,9,4
68,10,4
44,2,5
49,3,5
37,4,5
41,5,5
45,6,5
58,7,5
21,8,5
25,9,5
85,2,6
79,3,6
86,4,6
36,5,6
18,6,6
71,7,6
39,8,6
16,3,7
24,4,7
19,5,7
63,6,7
42,7,7
38,8,7
74,9,7
33,3,8
47,4,8
46,5,8
15,6,8
43,7,8
26,8,8
05,9,8
40,3,9
82,4,9
12,5,9
48,6,9
07,7,9
84,8,9
04,9,9
64,3,10
32,4,10
81,5,10
34,6,10
30,7,10
13,8,10
06,9,10
09,5,11
31,4,11
65,3,11
83,8,11
11,6,11
66,5,12
```

**Comment by stedy** [comment]
![](https://about-france.com/Map-france-reg.gif)

**Comment by jerbou** [comment]
This file still missing Island of Corse (2a, 2b)

**Comment by stedy** [comment]
Feel free to add them and I will update the grid accordinnly

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)
