### ISSUE TITLE
us_wi_counties_grid

### ISSUE THREAD

**Issue by aravamu2** [hafen/geofacet#230]
Grid for Wisconsin counties.

read_csv("https://coronadatascraper.com/timeseries.csv") %>% 
  timeseries %>% 
  filter(state == "Wisconsin",
         level == "county") %>% 
  as_data_frame() %>% 
  mutate(
    name = county,
         code = county %>% 
           str_remove(" County") %>% 
           str_to_lower() %>% 
           str_remove("[:punct:]")
  ) %>% 
  ggplot(aes(x = date, y = cases)) + 
  geom_line(aes(color = cases)) + 
  scale_color_distiller(palette = "RdPu",
                        direction = 1) +
  facet_geo(~ code, grid = mygrid) + 
  theme_classic() + 
  theme(
        # axis.text.x = element_blank(),
        # axis.line.x = element_blank(),
        # axis.ticks.x = element_blank(),
        axis.text.x = element_text(size = 6,
                                   hjust = 1,
                                   angle = 30),
        axis.text.y = element_text(size = 6),
        strip.background = element_blank(),
        strip.text = element_text(size = 6)
  ) + 
  theme(
    panel.spacing = unit(0.2, "lines"),
    legend.position = "none"
  )

![image](https://user-images.githubusercontent.com/12982380/81262532-a40f7700-9003-11ea-8989-06b3977884d7.png)

Grid data:

```
name,code,row,col
Douglas County,douglas,1,3
Bayfield County,bayfield,1,4
Washburn County,washburn,2,3
Sawyer County,sawyer,2,4
Ashland County,ashland,2,5
Iron County,iron,2,6
Oneida County,oneida,2,7
Vilas County,vilas,2,8
Polk County,polk,3,1
Burnett County,burnett,3,2
Barron County,barron,3,3
Chippewa County,chippewa,3,4
Rusk County,rusk,3,5
Price County,price,3,6
Lincoln County,lincoln,3,7
Langlade County,langlade,3,8
Forest County,forest,3,9
Florence County,florence,3,10
Marinette County,marinette,3,11
St. Croix County,st croix,4,2
Dunn County,dunn,4,3
Eau Claire County,eau claire,4,4
Clark County,clark,4,5
Taylor County,taylor,4,6
Marathon County,marathon,4,7
Shawano County,shawano,4,8
Menominee County,menominee,4,9
Oconto County,oconto,4,10
Calumet County,calumet,4,11
Door County,door,4,13
Pierce County,pierce,5,2
Pepin County,pepin,5,3
Trempealeau County,trempealeau,5,4
Jackson County,jackson,5,5
Wood County,wood,5,6
Portage County,portage,5,7
Waushara County,waushara,5,8
Waupaca County,waupaca,5,9
Outagamie County,outagamie,5,10
Brown County,brown,5,11
Kewaunee County,kewaunee,5,12
Buffalo County,buffalo,6,3
La Crosse County,la crosse,6,4
Monroe County,monroe,6,5
Juneau County,juneau,6,6
Adams County,adams,6,7
Green Lake County,green lake,6,8
Winnebago County,winnebago,6,9
Washington County,washington,6,10
Sheboygan County,sheboygan,6,11
Manitowoc County,manitowoc,6,12
Vernon County,vernon,7,5
Richland County,richland,7,6
Columbia County,columbia,7,7
Marquette County,marquette,7,8
Dodge County,dodge,7,9
Fond du Lac County,fond du lac,7,10
Ozaukee County,ozaukee,7,11
Crawford County,crawford,8,5
Iowa County,iowa,8,6
Sauk County,sauk,8,7
Dane County,dane,8,8
Jefferson County,jefferson,8,9
Waukesha County,waukesha,8,10
Milwaukee County,milwaukee,8,11
Grant County,grant,9,5
Lafayette County,lafayette,9,6
Green County,green,9,7
Rock County,rock,9,8
Walworth County,walworth,9,9
Kenosha County,kenosha,9,10
Racine County,racine,9,11
```

**Comment by stedy** [comment]
![](https://www.dhs.wisconsin.gov/sites/default/files/wi-counties.gif)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by hafen** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/2/25/Wisconsin-counties-map.gif)
