### ISSUE TITLE
new grid: 'norway_grid'

### ISSUE THREAD

**Issue by NanAmalie1** [hafen/geofacet#232]
Grid of counties in Norway

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"code","row","col","name"
"Finnmark",1,7,"Finnmark"
"Troms",2,6,"Troms"
"Nordland",3,5,"Nordland"
"More og Romsdal",4,3,"More og Romsdal"
"Trondelag",4,4,"Trondelag"
"Hedmark",5,4,"Hedmark"
"Sogn og Fjordane",5,2,"Sogn og Fjordane"
"Oppland",5,3,"Oppland"
"Akershus",6,4,"Akershus"
"Oslo",6,3,"Oslo"
"Buskerud",6,2,"Buskerud"
"Hordaland",6,1,"Hordaland"
"Telemark",7,2,"Telemark"
"Rogaland",7,1,"Rogaland"
"Vestfold",7,3,"Vestfold"
"Ostfold",7,4,"Ostfold"
"Aust-Agder",8,3,"Aust-Agder"
"Vest-Agder",8,2,"Vest-Agder"
```

**Comment by stedy** [comment]
![](https://www.researchgate.net/publication/321967815/figure/fig1/AS:574001933819904@1513864133585/Counties-in-Norway-per-December-2017-numbered-according-to-Statistics-Norway-Map-source.png)

**Comment by stedy** [comment]
This grid was added to [geofacet version 0.2](https://cran.r-project.org/web/packages/geofacet/index.html)

**Comment by hafen** [comment]
![](https://www.familysearch.org/en/wiki/img_auth.php/6/6c/Norway_2x2.jpg)
