### ISSUE TITLE
minor: Note shows up when grid is from package

### ISSUE THREAD

**Issue by ahcyip** [hafen/geofacet#250]
Using
`facet_geo(vars(state), grid = us_state_grid1, scales = "fixed") `
still shows the error message:

Note: You provided a user-specified grid. If this is a generally-useful grid, please consider submitting it to become a part of the geofacet package. You can do this easily by calling:
  grid_submit(__grid_df_name__)

**Comment by hafen** [comment]
If an explicit data frame is provided, it always assumes that it is a user-specified grid. To not print the message in this case, it would need to do an equivalence test across all existing grid data frames, which I don't thing is a good idea to implement.

If instead you specified `grid = "us_state_grid1"`, you would not get the message. Also note that this is not an error, just a message to users that helps encourage sharing grids.
