### ISSUE TITLE
new grid: 'Syria Governorates'

### ISSUE THREAD

**Issue by jschon637** [hafen/geofacet#251]
Grid of ADM-1 units (governorates) for Syria

See map of governorates labelled here: https://data2.unhcr.org/en/documents/details/69809

Grid data:

```
"code","name","row","col"
"1","Al-Hasakeh",1,5
"2","Aleppo",1,2
"3","Ar Raqqah",1,3
"4","As Sweida",6,3
"5","Damascus",5,2
"6","Dar`a",6,2
"7","Deir ez-Zour",2,4
"8","Hamaa",3,2
"9","Homs",4,3
"10","Idlib",2,2
"11","Lattakia",2,1
"12","Quneitra",6,1
"13","Rural Damascus",5,3
"14","Tartous",3,1
```

**Comment by stedy** [comment]
![](https://sawsanrifaee.files.wordpress.com/2014/03/syrie49.gif)

**Comment by jschon637** [comment]
Thank you. Yes, that map is good. I would just prefer to spell the governorate names the way that I specified.

**Comment by stedy** [comment]
ohh gotcha, so then the issue is adding an image to this issue for further reference. Is there an image from that UNHCR pdf that you can link to?

**Comment by jschon637** [comment]
The image is good. I just don't want the labels spelled like that.

**Comment by jschon637** [comment]
![Syria_adm1_image](https://user-images.githubusercontent.com/65607801/88221810-ff302d80-cc32-11ea-9cab-4db23937e2db.jpg)

**Comment by jschon637** [comment]
The above is in case you need a blank map.
