### ISSUE TITLE
new grid: 'ro_county_grid_v1'

### ISSUE THREAD

**Issue by alexfg** [hafen/geofacet#265]
Grid of Romanian counties

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"name","code","row","col"
"Maramures","MM",1,4
"Botosani","BT",1,6
"Satu Mare","SM",1,3
"Suceava","SV",2,5
"Bistrita-Nasaud","BN",2,4
"Neamt","NT",2,6
"Salaj","SJ",2,3
"Bihor","BH",2,2
"Iasi","IS",2,7
"Cluj","CJ",3,3
"Harghita","HR",3,5
"Bacau","BC",3,6
"Arad","AR",3,2
"Mures","MS",3,4
"Vaslui","VS",3,7
"Hunedoara","HD",4,2
"Brasov","BV",4,5
"Covasna","CV",4,6
"Timis","TM",4,1
"Alba","AB",4,3
"Sibiu","SB",4,4
"Vrancea","VN",4,7
"Galati","GL",4,8
"Caras-Severin","SV",5,1
"Gorj","GJ",5,2
"Arges","AG",5,4
"Prahova","PH",5,6
"Valcea","VL",5,3
"Dambovita","DB",5,5
"Buzau","BZ",5,7
"Braila","BR",5,8
"Tulcea","TL",5,9
"Mehedinti","MH",6,2
"Dolj","DJ",6,3
"Municipiul Bucuresti","B",6,5
"Olt","OT",6,4
"Ilfov","IF",6,6
"Ialomita","IL",6,7
"Constanta","CT",6,8
"Teleorman","TR",7,5
"Giurgiu","GR",7,6
"Calarasi","CL",7,7
```

**Comment by stedy** [comment]
![](http://travelsfinders.com/wp-content/uploads/2017/05/romania-map-with-counties-_1.gif)
