### ISSUE TITLE
Scot_Local_Authority

### ISSUE THREAD

**Issue by AndrewAiton** [hafen/geofacet#266]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
NAME,row,col
Shetland Islands,1,5
Orkney Islands,2,4
Na h-Eileanan an Iar,3,1
Highland,3,3
Moray,3,4
Aberdeenshire,3,5
Aberdeen,3,6
Argyll & Bute,4,3
Angus,4,7
Perth & Kinross,4,5
Stirling,4,4
Dundee,4,6
West Dunbartonshire,5,3
East Dunbartonshire,5,4
Falkirk,5,5
Clackmannanshire,5,6
Fife,5,7
Renfrewshire,6,3
North Lanarkshire,6,6
Inverclyde,6,2
East Renfrewshire,6,4
Glasgow,6,5
West Lothian,6,7
Edinburgh,6,8
Midlothian,7,6
East Ayrshire,7,4
East Lothian,7,7
North Ayrshire,7,3
South Lanarkshire,7,5
Dumfries & Galloway,8,4
South Ayrshire,8,3
Scottish Borders,8,5
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Scotland_Administrative_Map_2009.png/800px-Scotland_Administrative_Map_2009.png)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
