### ISSUE TITLE
new grid: 'dk_cph_grid1'

### ISSUE THREAD

**Issue by Straubinger** [hafen/geofacet#269]
Grid of the 10 districts of Copenhagen, Denmark.

Grid data:

```
row,col,code,name
1,1,7,Brønshøj-Husum
1,2,8,Bispebjerg
1,4,2,Østerbro
1,3,3,Nørrebro
2,1,6,Vanløse
2,3,1,Indre By
3,4,9,Amager Øst
3,3,10,Amager Vest
3,1,5,Valby
3,2,4,Vesterbro-Kgs. Enghave
```

![map](https://upload.wikimedia.org/wikipedia/commons/6/62/Districts_of_Copenhagen_urban_area.png)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
