### ISSUE TITLE
new grid: 'bolivia_grid'

### ISSUE THREAD

**Issue by tartagalensis** [hafen/geofacet#275]
Grid of Departamental Political Division of Bolivia

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"col","row","code","name_es"
1,1,"BO-N","Pando"
1,2,"BO-L","La Paz"
2,2,"BO-C","Cochabamba"
3,2,"BO-B","Beni"
1,3,"BO-O","Oruro"
2,3,"BO-P","Potosí"
3,3,"BO-H","Chuquisaca"
4,3,"BO-S","Santa Cruz"
3,4,"BO-T","Tarija"
```
![MAPA BOL](https://user-images.githubusercontent.com/46819023/96675402-318c1c80-1341-11eb-9ab7-29ab0f6139a8.png)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
