### ISSUE TITLE
new grid: 'aus_grid1'

### ISSUE THREAD

**Issue by jonocarroll** [hafen/geofacet#3]
Australian States and Territories

```
"code","row","col","name"
"WA",3,1,"Western Australia"
"NT",1,2,"Northern Territory"
"SA",5,2,"South Australia"
"QLD",2,3,"Queensland"
"NSW",4,3,"New South Wales"
"ACT",5,3,"Australian Capital Territory"
"VIC",6,3,"Victoria"
"TAS",7,3,"Tasmania"
```

![auspopulation](https://cloud.githubusercontent.com/assets/9496865/26333407/92358868-3f9c-11e7-87ce-af667dca71d9.png)

**Comment by jonocarroll** [comment]
SA could just as easily be on row `4`.

Is it an issue that we can't have an entirely blank row/column? A gap between VIC and TAS would have been nice.

**Comment by hafen** [comment]
Awesome thanks!

I actually should require people to provide an example as you have done here. Any chance you could share the data and code to produce the plot?

I haven't tried a grid with a blank row but it makes sense to have that here. Did you try it and it didn't work? If so, can you submit that as another issue and I'll look into it.

About the layout: Creating this grids will always be subjective so I'm not sure how to deal with different opinions people might have about how things should be laid out other than making many options available. In general, the goal with a grid is to make the grid as compact as the geography will possibly allow, which often comes with sacrificing very accurate fidelity to the original geography. The idea is to just have things roughly where you might expect them when scanning a map, and it's nice to preserve regions that touch each other as much as possible. I think some compaction could happen here. For example, Can Queensland be right on top of New South Wales? Likewise, can Northern Territory and Southern Australia also be touching?

**Comment by hafen** [comment]
BTW if you don't like my opinions we can always have multiple grids :).

**Comment by jonocarroll** [comment]
Code to produce this example:

https://gist.github.com/jonocarroll/88b86cea90e798668dc25d43d0211180

I wanted to spread out the grid vertically a little since ACT and VIC are pretty much entirely South of SA. The restriction of equal-sizes means this will never fit perfectly. I've added another alternative (#5).

**Comment by jonocarroll** [comment]
FYI:

![images](https://cloud.githubusercontent.com/assets/9496865/26334627/75a729d2-3fa5-11e7-88af-a1dd86b7ddf3.png)
