### ISSUE TITLE
new grid

### ISSUE THREAD

**Issue by accostales** [hafen/geofacet#319]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row	col	Abreviatura	Nombre,row,col
1	1	PRI	Pinar del Río,1,1
2	2	ART	Artemisa,1,2
3	4	LHA	La Habana,1,3
2	5	MAY	Mayabeque,1,4
2	5	MTZ	Matanzas,1,5
2	6	VCL	Villa Clara,1,6
2	7	CFG	Cienfuegos,2,1
3	8	SSP	Sancti Spiritus,2,2
3	9	CEV	Ciego de Ávila,2,3
4	10	CAM	Camagüey,2,4
4	11	LTA	Las Tunas,2,5
4	12	HOL	Holguín,2,6
5	12	GRA	Granma,3,1
5	14	SCU	Santiago de Cuba,3,2
5	15	GTM	Guantánamo,3,3
3	2	ISJ	Isla de la Juventud,3,4
```

**Comment by stedy** [comment]
![](https://www.fellowship.com/javax.faces.resource/images/cuba/xcuba-map-of-provinces.jpg.pagespeed.ic.PuoyMF_NtY.jpg)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
