### ISSUE TITLE
new grid: 'geo_grid'

### ISSUE THREAD

**Issue by nasrashvilin** [hafen/geofacet#320]
Georgia Regions

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
1,1,"AB","Abkhazia"
2,3,"RC","Racha_Lechkhumi"
2,4,"TS","Tskhinvali"
2,2,"SM","Samegrelo"
2,6,"TI","Mtskheta_Mtianeti"
3,4,"SH","Shida_Kartli"
3,3,"IM","Imereti"
3,5,"TB","Tbilisi"
3,2,"GR","Guria"
4,6,"KA","Kakheti"
4,3,"SJ","Samtskhe_Javakheti"
4,2,"AD","Adjara"
4,5,"KV","Kvemo_Kartli"
```

**Comment by stedy** [comment]
![](https://global-goose.com/wp-content/uploads/2019/07/georgia-map.jpg)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
