### ISSUE TITLE
scotland_local_authority_map

### ISSUE THREAD

**Issue by davidhen** [hafen/geofacet#33]
Scotland's Local Authorities by approximate geographic location.

Grid data:

```
Local Authority,row,col
Shetland Islands,1,6
Orkney Islands,2,5
Eilean Siar,3,2
Aberdeenshire,4,8
Moray,4,7
Highland,4,4
Aberdeen City,5,8
Argyll

**Comment by davidhen** [comment]
Hi - I use the Geo Grid designer to create this and the "submit grid to github" tab. Don't think it copied over completely? I have copied the R code below.

mygrid <- data.frame(
  Local Authority = c("Shetland Islands", "Orkney Islands", "Eilean Siar", "Aberdeenshire", "Moray", "Highland", "Aberdeen City", "Argyll & Bute", "Perth & Kinross", "Angus", "Dundee City", "Fife", "Clackmannanshire", "Stirling", "East Dunbartonshire", "West Dunbartonshire", "Falkirk", "North Ayrshire", "Inverclyde", "Glasgow City", "North Lanarkshire", "West Lothian", "Edinburgh", "East Lothian", "South Ayrshire", "South Lanarkshire", "East Renfrewshireý", "Renfrewshire", "Midlothian", "East Ayrshire", "Scottish Borders", "Dumfries & Galloway"),
  row = c(1, 2, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 12),
  col = c(6, 5, 2, 8, 7, 4, 8, 3, 5, 7, 6, 6, 5, 4, 3, 2, 4, 1, 2, 3, 4, 5, 6, 7, 1, 4, 3, 2, 6, 2, 6, 2)
)
geofacet::grid_preview(mygrid)

**Comment by hafen** [comment]
Thanks! The csv grid data in the first comment is sufficient. I'll add this as soon as I can.

**Comment by hafen** [comment]
This helped me find a bug in the grid designer - it wasn't encoding ampersands correctly which is why things got cut off. This is fixed now.

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/28044967-3b508570-658f-11e7-99b5-b1d73c765c2e.png)

**Comment by hafen** [comment]
I added this as `scotland_local_authority_grid1`. I also looked up some other codes and added those.

**Comment by davidhen** [comment]
Awesome! Thanks
![alt_missing_living_arr-1](https://user-images.githubusercontent.com/26236404/28067901-1b6ccc12-663b-11e7-8cfc-127501aef1fb.png)
