### ISSUE TITLE
ch_vaud_districts

### ISSUE THREAD

**Issue by mick-weber** [hafen/geofacet#334]
List of districts for the Canton de Vaud, one of the 26 cantons of Switzerland. There are 10 Districts since a fusion in 2008.

Grid data:

```
name,code,row,col
Broye-Vully,2222,1,4
Jura-Nord vaudois,2224,1,2
Lausanne,2225,2,3
Riviera-Pays-d'Enhaut,2230,2,5
Lavaux-Oron,2226,2,4
Ouest lausannois,2229,2,2
Morges,2227,2,1
Gros-de-Vaud,2223,1,3
Aigle,2221,3,5
Nyon,2228,3,1
```

![map](https://www.bassin-lemanique.com/WG8-Websites_de_Canton_de_Vaud)

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/6/64/Karte_Kanton_Waadt_Bezirke_2008.png)

**Comment by vdes2020** [comment]
How do we access it from geofacet ? Thanks !

**Comment by hafen** [comment]
It will be merged in with the package on the next release. I hope to do this soon.

In the mean time, since you created it, you can use the grid locally by passing the grid data frame you created to facet_geo. The grid submission is simply a service to the community so that others can use the grids as well.

Let me know if you have any issues using your grid.

**Comment by vdes2020** [comment]
Thanks for the precision, I wasn't sure how to use it locally. Could you please specify how to pass the grid (from copy/pasting above) as an argument for `facet_geo(grid = ...)` ? Many thanks for your help !

**Comment by hafen** [comment]
First, it looks like your grid needs some updates to conform with the package. It must have columns "name" and "code". Here's an update of the grid (you can probably come up with better codes than what I did).

```
name,code,row,col
Broye-Vully,br,1,4
Jura-Nord vaudois,ju,1,2
Lausanne,la,2,3
Riviera-Pays-d'Enhaut,ri,2,5
Lavaux-Oron,lv,2,4
Ouest lausannois,ol,2,2
Morges,mo,2,1
Gros-de-Vaud,gr,1,3
Aigle,ai,3,5
Nyon,ny,3,1
```

To use it in R, you need to get it into the form of a data frame. There's many ways to do this but here's one:

```r
grd <- read.csv(textConnection("name,code,row,col
Broye-Vully,br,1,4
Jura-Nord vaudois,ju,1,2
Lausanne,la,2,3
Riviera-Pays-d'Enhaut,ri,2,5
Lavaux-Oron,lv,2,4
Ouest lausannois,ol,2,2
Morges,mo,2,1
Gros-de-Vaud,gr,1,3
Aigle,ai,3,5
Nyon,ny,3,1"))

library(geofacet)

# preview the grid
geofacet::grid_preview(grd)

# use in a plot (fill in the blanks)
ggplot(...) +
  ...
  facet_geo(~ ..., data = grd)
```

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
