### ISSUE TITLE
new grid: 'KR_Seoul_kjh'

### ISSUE THREAD

**Issue by kjhnav** [hafen/geofacet#340]
Modified Seoul with Han river

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"name","row","col","code"
"Gangseo",5,1,"Gangseo"
"Yangcheon",6,1,"Yangcheon"
"Guro",7,1,"Guro"
"Eunpyeong",2,2,"Eunpyeong"
"Seodaemun",3,2,"Seodaemun"
"Mapo",4,2,"Mapo"
"Yeongdeungpo",6,2,"Yeongdeungpo"
"Gumcheon",7,2,"Gumcheon"
"Seongbuk ",2,3,"Seongbuk "
"Jongno",3,3,"Jongno"
"Jung",4,3,"Jung"
"Yongsan",5,3,"Yongsan"
"Dongjak",7,3,"Dongjak"
"Gwanak",8,3,"Gwanak"
"Dobong",1,4,"Dobong"
"Gangbuk",2,4,"Gangbuk"
"Dongdaemun",3,4,"Dongdaemun"
"Seongdong",4,4,"Seongdong"
"Gangnam",6,4,"Gangnam"
"Seocho",7,4,"Seocho"
"Nowon",2,5,"Nowon"
"Jungnang",3,5,"Jungnang"
"Gwangjin",4,5,"Gwangjin"
"Songpa",6,5,"Songpa"
"Gangdong",5,6,"Gangdong"
```

**Comment by stedy** [comment]
![](https://www.snapshotseoul.com/wp-content/uploads/2019/09/districtsinseoul_administrativedistrictsofseoul1-1024x768.jpg)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
