### ISSUE TITLE
new grid: 'Korea_sido_Eng'

### ISSUE THREAD

**Issue by kjhnav** [hafen/geofacet#341]
Korea large city and province in English

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
2,1,"Incheon","Incheon"
3,1,"Chungcheongnam-do","Chungcheongnam-do"
4,1,"Jeollabuk-do","Jeollabuk-do"
5,1,"Jeollanam-do","Jeollanam-do"
6,1,"Gwangju","Gwangju"
8,1,"Jeju-do","Jeju-do"
1,2,"Gyeonggi-do","Gyeonggi-do"
2,2,"Seoul","Seoul"
3,2,"Chungcheongbuk-do","Chungcheongbuk-do"
4,2,"Sejong","Sejong"
5,2,"Daejeon","Daejeon"
2,3,"Gangwon-do","Gangwon-do"
3,3,"Gyeongsangbuk-do","Gyeongsangbuk-do"
4,3," Daegu"," Daegu"
5,3,"Gyeongsangnam-do","Gyeongsangnam-do"
6,3,"Ulsan","Ulsan"
7,3,"Busan","Busan"
```

**Comment by stedy** [comment]
![](https://th.bing.com/th/id/OIP.-lfWHkH-f5T7teA7ODvkgAHaHm?pid=ImgDet&rs=1)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
