### ISSUE TITLE
new grid: 'OECD2'

### ISSUE THREAD

**Issue by kjhnav** [hafen/geofacet#342]
OECD grid

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
1,3,"IE","Ireland"
1,7,"FI","Finland"
1,6,"SE","Sweden"
1,2,"IS","Iceland"
1,5,"NO","Norway"
2,5,"DK","Denmark"
2,9,"EE","Estonia"
2,8,"LV","Latvia"
2,3,"GB","United Kingdom"
3,6,"DE","Germany"
3,5,"NL","Netherlands"
3,7,"PL","Poland"
3,1,"CA","Canada"
4,5,"CH","Switzerland"
4,6,"BE","Belgium"
4,7,"CZ","Czech Republic"
4,4,"FR","France"
4,8,"SK","Slovakia"
4,1,"US","United States"
5,4,"ES","Spain"
5,5,"LU","Luxembourg"
5,7,"HU","Hungary"
5,6,"AT","Austria"
5,3,"PT","Portugal"
5,1,"MX","Mexico"
6,5,"IT","Italy"
6,6,"SI","Slovenia"
2,11,"KR","Republic of Korea"
2,12,"JP","Japan"
4,10,"GR","Greece"
4,11,"TR","Turkey"
5,11,"IL","Israel"
7,11,"AU","Australia"
7,12,"NZ","New Zealand"
7,1,"CL","Chile"
```

**Comment by stedy** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/2/26/OECD_Countries_Blue.png)
