### ISSUE TITLE
inversion of 2 departements in France

### ISSUE THREAD

**Issue by Valexandre** [hafen/geofacet#343]
Hi !
I cannot manage to suggest a change in the fr_departements_grid1.rda file but there is an inversion between Haute-Corse (2B that needs to be row 14) and Corse du Sud (2A that needs to be row 15).
Thanks !

**Comment by Valexandre** [comment]
Thanks @stedy

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
