### ISSUE TITLE
new grid: Bolivia by departamentos

### ISSUE THREAD

**Issue by ccsuehara** [hafen/geofacet#344]
row,	col,	departamento
1,	1,	Pando
2,	1,	La Paz
3,	1,	Oruro
4,	1,	Potosí
2,	2,	Beni
3,	2,	Cochabamba
4,	2,	Chuquisaca
5,	2,	Tarija
3,	3,	Santa Cruz

![image](https://user-images.githubusercontent.com/12155945/128909328-951c92d2-b544-4ed8-a26b-64c14f267346.png)

![image](https://user-images.githubusercontent.com/12155945/128909409-35809a9c-b395-4ddc-95e7-666aa508d2a0.png)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
