### ISSUE TITLE
new TN grid

### ISSUE THREAD

**Issue by AminGhrabi** [hafen/geofacet#354]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row,col,code,name
1,3,TN-17,Bizerte
2,2,TN-21,Beja
2,4,TN-12,Ariana
2,3,TN-14,Mannouba
2,6,TN-15,Nabeul
3,1,TN-22,Jendouba
3,4,TN-11,Tunis
3,2,TN-24,Siliana
3,5,TN-13,Ben Arous
4,3,TN-41,Kairouan
3,3,TN-16,Zaghouan
4,4,TN-31,Sousse
5,2,TN-23,Le Kef
5,4,TN-33,Mahdia
5,5,TN-32,Monastir
6,3,TN-43,Sidi Bouzid
6,2,TN-42,Kasserine
6,4,TN-34,Sfax
7,5,TN-51,Gabes
7,1,TN-62,Tozeur
8,3,TN-63,Kebili
8,6,TN-52,Medenine
8,2,TN-61,Gafsa
9,4,TN-53,Tataouine
```

![map](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Ariana_in_Tunisia.svg/320px-Ariana_in_Tunisia.svg.png)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
