### ISSUE TITLE
MN grid

### ISSUE THREAD

**Issue by chadrent** [hafen/geofacet#369]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
,row,col
Kittson County,1,1
Roseau County,1,2
Lake of the Woods County,1,4
Koochiching County,1,5
Saint Louis County,1,8
Lake County,1,10
Cook County,1,11
Marshall County,2,1
Polk County,3,1
Pennington County,3,3
Carlton County,3,7
Itasca County,4,6
Red Lake County,4,3
Beltrami County,5,4
Mahnomen County,5,2
Norman County,5,1
Clearwater County,5,3
Aitkin County,6,6
Cass County,6,5
Hubbard County,6,4
Becker County,6,2
Clay County,6,1
Pine County,7,8
Kanabec County,7,7
Mille Lacs County,7,6
Otter Tail County,7,2
Wilkin County,7,1
Wadena County,7,4
Crow Wing County,7,5
Chisago County,8,8
Isanti County,8,7
Morrison County,8,5
Todd County,8,4
Douglas County,8,3
Grant County,8,2
Traverse County,8,1
Stearns County,9,4
Benton County,9,5
Washington County,9,8
Anoka County,9,7
Pope County,9,3
Stevens County,9,2
Wright County,10,6
Sherburne County,10,5
Ramsey County,10,7
Swift County,10,2
Big Stone County,10,1
McLeod County,11,5
Carver County,11,6
Hennepin County,11,7
Meeker County,11,4
Kandiyohi County,11,3
Chippewa County,11,2
Lac qui Parle County,11,1
Dakota County,12,8
Scott County,12,6
Sibley County,12,5
Renville County,12,3
Yellow Medicine County,12,1
Wabasha County,13,9
Goodhue County,13,8
Rice County,13,7
Le Sueur County,13,6
Nicollet County,13,5
Brown County,13,4
Redwood County,13,3
Lyon County,13,2
Lincoln County,13,1
Winona County,14,10
Olmsted County,14,9
Dodge County,14,8
Steele County,14,7
Waseca County,14,6
Blue Earth County,14,5
Watonwan County,14,4
Cottonwood County,14,3
Murray County,14,2
Pipestone County,14,1
Houston County,15,9
Fillmore County,15,8
Mower County,15,7
Freeborn County,15,6
Faribault County,15,5
Martin County,15,4
Jackson County,15,3
Nobles County,15,2
Rock County,15,1
```

![map](https://hafen.github.io/grid-designer/#data=%2Crow%2Ccol%0AKittson%20County%2C1%2C1%0ARoseau%20County%2C1%2C2%0ALake%20of%20the%20Woods%20County%2C1%2C4%0AKoochiching%20County%2C1%2C5%0ASaint%20Louis%20County%2C1%2C8%0ALake%20County%2C1%2C10%0ACook%20County%2C1%2C11%0AMarshall%20County%2C2%2C1%0APolk%20County%2C3%2C1%0APennington%20County%2C3%2C3%0ACarlton%20County%2C3%2C7%0AItasca%20County%2C4%2C6%0ARed%20Lake%20County%2C4%2C3%0ABeltrami%20County%2C5%2C4%0AMahnomen%20County%2C5%2C2%0ANorman%20County%2C5%2C1%0AClearwater%20County%2C5%2C3%0AAitkin%20County%2C6%2C6%0ACass%20County%2C6%2C5%0AHubbard%20County%2C6%2C4%0ABecker%20County%2C6%2C2%0AClay%20County%2C6%2C1%0APine%20County%2C7%2C8%0AKanabec%20County%2C7%2C7%0AMille%20Lacs%20County%2C7%2C6%0AOtter%20Tail%20County%2C7%2C2%0AWilkin%20County%2C7%2C1%0AWadena%20County%2C7%2C4%0ACrow%20Wing%20County%2C7%2C5%0AChisago%20County%2C8%2C8%0AIsanti%20County%2C8%2C7%0AMorrison%20County%2C8%2C5%0ATodd%20County%2C8%2C4%0ADouglas%20County%2C8%2C3%0AGrant%20County%2C8%2C2%0ATraverse%20County%2C8%2C1%0AStearns%20County%2C9%2C4%0ABenton%20County%2C9%2C5%0AWashington%20County%2C9%2C8%0AAnoka%20County%2C9%2C7%0APope%20County%2C9%2C3%0AStevens%20County%2C9%2C2%0AWright%20County%2C10%2C6%0ASherburne%20County%2C10%2C5%0ARamsey%20County%2C10%2C7%0ASwift%20County%2C10%2C2%0ABig%20Stone%20County%2C10%2C1%0AMcLeod%20County%2C11%2C5%0ACarver%20County%2C11%2C6%0AHennepin%20County%2C11%2C7%0AMeeker%20County%2C11%2C4%0AKandiyohi%20County%2C11%2C3%0AChippewa%20County%2C11%2C2%0ALac%20qui%20Parle%20County%2C11%2C1%0ADakota%20County%2C12%2C8%0AScott%20County%2C12%2C6%0ASibley%20County%2C12%2C5%0ARenville%20County%2C12%2C3%0AYellow%20Medicine%20County%2C12%2C1%0AWabasha%20County%2C13%2C9%0AGoodhue%20County%2C13%2C8%0ARice%20County%2C13%2C7%0ALe%20Sueur%20County%2C13%2C6%0ANicollet%20County%2C13%2C5%0ABrown%20County%2C13%2C4%0ARedwood%20County%2C13%2C3%0ALyon%20County%2C13%2C2%0ALincoln%20County%2C13%2C1%0AWinona%20County%2C14%2C10%0AOlmsted%20County%2C14%2C9%0ADodge%20County%2C14%2C8%0ASteele%20County%2C14%2C7%0AWaseca%20County%2C14%2C6%0ABlue%20Earth%20County%2C14%2C5%0AWatonwan%20County%2C14%2C4%0ACottonwood%20County%2C14%2C3%0AMurray%20County%2C14%2C2%0APipestone%20County%2C14%2C1%0AHouston%20County%2C15%2C9%0AFillmore%20County%2C15%2C8%0AMower%20County%2C15%2C7%0AFreeborn%20County%2C15%2C6%0AFaribault%20County%2C15%2C5%0AMartin%20County%2C15%2C4%0AJackson%20County%2C15%2C3%0ANobles%20County%2C15%2C2%0ARock%20County%2C15%2C1)

**Comment by hafen** [comment]
Added in https://github.com/hafen/grid-designer/pull/8
