### ISSUE TITLE
Ukraine

### ISSUE THREAD

**Issue by woldemarg** [hafen/geofacet#37]
Example if this grid in action - https://github.com/woldemarg/crimes_map

Grid data:

```
region,row,col
Сумська,1,6
Чернігівська,1,5
Волинська,2,1
Київ,2,4
Київська,2,5
Житомирська,2,3
Рівненська,2,2
Полтавська,2,6
Харківська,2,7
Луганська,2,8
Львівська,3,1
Черкаська,3,5
Вінницька,3,4
Хмельницька,3,3
Тернопільська,3,2
Дніпропетровська,3,7
Кіровоградська,3,6
Донецька,3,8
Закарпатська,4,1
Івано-Франківська,4,2
Запорізька,4,7
Одеська,4,4
Миколаївська,4,5
Херсонська,4,6
Чернівецька,4,3
АР Крим,5,6
Севастополь,5,7
```

![map](http://images1.fanpop.com/images/image_uploads/Ukrainian-map-ukraine-1153187_730_505.gif)

**Comment by hafen** [comment]
Thanks! That's a really nice plot. I added the grid as `ua_region_grid1` and added some additional codes (see [here](https://github.com/hafen/grid-designer/blob/master/grids/ua_region_grid1.csv)).
