### ISSUE TITLE
new grid: 'SF_Bay_area_9_counties'

### ISSUE THREAD

**Issue by Eunoia** [hafen/geofacet#39]
Grid of the close in, 9 San Francisco Bay Area counties.

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"code","name","row","col"
"Sonoma County","Sonoma County",1,1
"Napa County","Napa County",1,2
"Solano Count","Solano Count",1,3
"Marin County","Marin County",2,1
"Contra Costa County","Contra Costa County",2,3
"Alameda County","Alameda County",3,3
"San Francisco County","San Francisco County",3,1
"San Mateo County","San Mateo County",4,1
"Santa Clara County","Santa Clara County",4,2
```

**Comment by Eunoia** [comment]
Test pull request, please do not merge!

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/28043128-53be650a-6585-11e7-920e-4ad9a13bf1a5.png)

**Comment by hafen** [comment]
Thanks! I have added this to the package.
