### ISSUE TITLE
Make this an official ggplot extension?

### ISSUE THREAD

**Issue by ahcyip** [hafen/geofacet#430]
I use facet_geo a lot and think it would feature really well as an "official" ggplot extension!
https://exts.ggplot2.tidyverse.org/gallery/

https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension
If you are a ggplot2 extension developer, you can add your extension by doing the following:

[Fork](https://help.github.com/articles/fork-a-repo/) this repository.
Create a png thumbnail of an interesting plot from your extension that will look good on a retina screen at 350x300 pixels and put this file in the images directory of this repository.
Add an entry for your extension in the _config.yml file of this repository with the meta data for your extension (copy another entry and modify). Please see below for guidance on the meta data.
Push your changes and [create a pull request](https://help.github.com/articles/creating-a-pull-request/). To ensure the quality of extensions added to the registry and consistency in how they are displayed, you should expect some amount of discussion during your pull request.

**Comment by ahcyip** [comment]
I drafted an entry for adding geofacet to the ggplot2 extensions gallery, where more people will discover geofacet.
https://github.com/ggplot2-exts/gallery/pull/196
Will keep you updated, and happy to incorporate any direction or comments from you

**Comment by hafen** [comment]
Awesome thanks for doing that! I took a look and I think it looks great.

Interestingly I wasn't aware of the gallery - it's cool to see that it's based off of the htmlwidgets gallery that I created.

**Comment by ahcyip** [comment]
I did see a reference to @hafenstats at the bottom of the page! So I'm pleased to make this full circle /double connection.

**Comment by ahcyip** [comment]
Completed at https://exts.ggplot2.tidyverse.org/gallery/

**Comment by hafen** [comment]
Thanks!
