### ISSUE TITLE
be_province_grid1

### ISSUE THREAD

**Issue by ericlecoutre** [hafen/geofacet#48]
Belgium facets at province level (except Brussels capital being a region in fact).
Code are ISIO_31662 codes, names are provided in three languages (French, Dutch, English).
Also, for convenience for Belgium Data Scientist, Belgium internal codes (NIS) are provided.

```
row,col,code,name_EN,name_NL, name_FR, NIS1, NIS4
1,3,BE-VAN, Antwerp, Anterwpen, Anvers, 1, 1000
2,1,BE-VWV, West Flanders, West-Vlaanderen, Flandre Occidentale, 3, 3000
2,2,BE-VOV, East Flanders, Oost-Vlaanderen, Flandre Orientale, 4, 4000
2,4,BE-VLI, Limburg, Limburg, Limbourg, 7, 7000
2,3,BE-VBR, Flemish Brabant, Vlaams-Brabant,Brabant Flamand, 2, 2000
3,2,BE-WHT, Hainaut, Henegouwen, Hainaut, 5, 5000
3,3,BE-WBR, Walloon Brabant, Waals-Brabant, Brabant Wallon, 2, 2000
3,4,BE-WLG, Liege, Luik, Liège, 6, 6000 
4,3,BE-WNA, Namur, Namen, Namur, 9, 9000
4,4,BE-WLX, Luxembourg, Luxemburg, Luxembourg, 8, 8000
5,1,BE-BRU, Brussels-Capital,Brussels Hoofdstedelik, Bruxelles Capitale,4, 4000
```

![map](http://www.eupedia.com/images/content/Belgium_Regions.gif)

**Comment by ericlecoutre** [comment]
Realized that every column must begin with name or code. Fixed that.
Cf.
[geofacet_be_map.txt](https://github.com/hafen/geofacet/files/1183094/geofacet_be_map.txt)

Provided an example of usage here:
https://github.com/ericlecoutre/geofacet_be_map

Kr,

Eric

**Comment by hafen** [comment]
Thanks! It's been added.
