### ISSUE TITLE
new grid: 'aus_grid2'

### ISSUE THREAD

**Issue by jonocarroll** [hafen/geofacet#5]
Australian States and Territories; an alternative grid with less whitespace.

```
"code","row","col","name"
"WA",2,1,"Western Australia"
"NT",1,2,"Northern Territory"
"SA",2,2,"South Australia"
"QLD",1,3,"Queensland"
"NSW",2,3,"New South Wales"
"ACT",3,4,"Australian Capital Territory"
"VIC",3,3,"Victoria"
"TAS",4,3,"Tasmania"
```

![auspopulation2](https://cloud.githubusercontent.com/assets/9496865/26334538/f4f44a40-3fa4-11e7-8cbc-6893bf8e7085.png)

**Comment by hafen** [comment]
I like this one! It agree it would be nice to have some space between Tasmania. I'll look into the empty row issue.

**Comment by hafen** [comment]
I just committed an update with this grid (https://github.com/hafen/geofacet/commit/1ac7b2ebaecb2b1f23e76c42535613a8a31a1a86). I also used the data you provided and your example - hope that's okay.

**Comment by hafen** [comment]
I just realized I used this grid calling it "aus_grid1". Do you want me to put the other grid in as well?

**Comment by jonocarroll** [comment]
I'm not fussed. Using whichever you think works best as "aus_grid1" is fine by me. If blank rows are permitted now I might see if I can make a better one and PR that.

**Comment by hafen** [comment]
Sounds good.
