### ISSUE TITLE
new grid

### ISSUE THREAD

**Issue by weiyunna** [hafen/geofacet#50]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
code	name,row,col
BJ	Beijing,1,1
TJ	Tianjin,1,2
HE	Hebei,1,3
SX	Shanxi,1,4
NM	Innermogolia,1,5
LN	Liaoning,1,6
JL	Jilin,1,7
HL	Heilongjiang,1,8
SH	Shanghai,2,1
JS	Jiangsu,2,2
ZJ	Zhejiang,2,3
AH	Anhui,2,4
FJ	Fujian,2,5
JX	Jiangxi,2,6
SD	Shandong,2,7
HA	Henan,2,8
HB	Hubei,3,1
HN	Hunan,3,2
GD	Guangdong,3,3
GX	Guangxi,3,4
HI	Hainan,3,5
CQ	Chongqing,3,6
SC	Sichuan,3,7
GZ	Guizhou,3,8
YN	Yunnan,4,1
XZ	Xizang,4,2
SN	Shaanxi,4,3
GS	Gansu,4,4
QH	Qinghai,4,5
NX	Ningxia,4,6
XJ	Xinjiang,4,7
TW	Taiwan,4,8
HK	Hongkong,5,1
MC	Macau,5,2
```

![map](http://www2m.biglobe.ne.jp/%257EZenTech/English/Map/China/index.htm)

**Comment by hafen** [comment]
I presume #57 has the final map so I'm closing all of these issues and only adding the grid provided in #57. If this is not the case please let me know.
