### ISSUE TITLE
China_Grid

### ISSUE THREAD

**Issue by weiyunna** [hafen/geofacet#52]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data: China province data 

```
code	name,row,col
HL	Heilongjiang,1,10
NM	Innermogolia,2,7
JL	Jilin,2,10
XJ	Xinjiang,2,1
BJ	Beijing,3,8
LN	Liaoning,3,9
NX	Ningxia,3,5
TJ	Tianjin,4,8
HE	Hebei,4,7
QH	Qinghai,4,2
HA	Henan,5,7
SX	Shanxi,5,6
SD	Shandong,5,8
GS	Gansu,5,4
HB	Hubei,6,6
AH	Anhui,6,7
SH	Shanghai,6,9
SN	Shaanxi,6,5
JS	Jiangsu,6,8
HN	Hunan,7,6
CQ	Chongqing,7,5
ZJ	Zhejiang,7,8
XZ	Xizang,7,2
SC	Sichuan,7,4
TW	Taiwan,8,10
JX	Jiangxi,8,7
GZ	Guizhou,8,5
FJ	Fujian,8,8
YN	Yunnan,9,4
GX	Guangxi,9,6
GD	Guangdong,9,7
MC	Macau,10,9
HK	Hongkong,10,10
HI	Hainan,11,7
```

**Comment by hafen** [comment]
I presume #57 has the final map so I'm closing all of these issues and only adding the grid provided in #57. If this is not the case please let me know.
