### ISSUE TITLE
Cantons of Switzerland: ch_cantons-de_grid1

### ISSUE THREAD

**Issue by tinu-schneider** [hafen/geofacet#58]
Hi Ryan

Thanks for your cool new package! Its great and helps a lot. 

I tried to generate a grid for the cantons (= member states) of Switzerland.
ISO_3166-2 is checked. As Switzerland has four official languages (German, French, Italian, Romansh) the names of the cantons vary depending on the chosen language (e.g. Bern, Bern**e**, Bern**a**, Bern**a**), see here: [https://en.wikipedia.org/wiki/Cantons_of_Switzerland](https://en.wikipedia.org/wiki/Cantons_of_Switzerland).

So I would add the 'de' into the grids name, because I use the German names ('de' stands for German).

An example is here:
[https://github.com/tinu-schneider/geofacet_CH_example](https://github.com/tinu-schneider/geofacet_CH_example)

With  the following  result: 
![plot_geofacet_ch](https://user-images.githubusercontent.com/854515/28745706-05c284b4-747e-11e7-9dcf-0950662dbb36.png)

Grid data:

```
row,col,code,name
1,5,SH,Schaffhausen
2,2,BS,Basel-Stadt
2,6,TG,Thurgau
2,5,ZH,Zürich
2,4,AG,Aargau
2,3,BL,Basel-Landschaft
2,7,SG,St. Gallen
3,2,JU,Jura
3,3,SO,Solothurn
3,5,ZG,Zug
3,6,AR,Appenzell A.Rh.
3,7,AI,Appenzell I.Rh.
3,4,LU,Luzern
4,3,BE,Bern
4,6,SZ,Schwyz
4,7,GL,Glarus
4,4,OW,Obwalden
4,5,NW,Nidwalden
4,2,NE,Neuenburg
5,8,GR,Graubünden
5,5,UR,Uri
5,2,VD,Waadt
5,3,FR,Freiburg
6,4,VS,Wallis
6,6,TI,Tessin
6,1,GE,Genf
```

![map](https://upload.wikimedia.org/wikipedia/commons/4/4a/Switzerland%2C_administrative_divisions_-_de_-_colored.svg)

**Comment by hafen** [comment]
Thanks! (and nice example). It has been added as `ch_cantons_grid1`.
