### ISSUE TITLE
new grid

### ISSUE THREAD

**Issue by marcospaollo** [hafen/geofacet#59]
rame(
  row = c(1,5,2,2),
  col = c(1,2,1,2),
  code = c("VV","BC","QC","AB"),
  name = c("Vila Velha","Barra do ceará","Quintino cunha","Antonio Bezerra"),
  stringsAsFactors = FALSE)

Grid data:

```

```

**Comment by hafen** [comment]
This doesn't follow the grid submission template so I'm closing the issue.
