### ISSUE TITLE
new grid: 'SA Grid'

### ISSUE THREAD

**Issue by jonmcalder** [hafen/geofacet#6]
South African Provinces

```
"code","row","col","name"
"WC",4,1,"Western Cape"
"EC",4,2,"Eastern Cape"
"NC",3,1,"Northern Cape"
"GP",2,2,"Gauteng"
"KZN",3,3,"KwaZulu-Natal"
"MP",2,3,"Mpumalanga"
"LP",1,3,"Limpopo"
"NW",2,1,"North West"
"FS",3,2,"Free State"
```

![image](http://www.exploresouthafrica.net/images/provmap.jpg)

![image](https://cloud.githubusercontent.com/assets/5055818/26379726/23d219f2-401b-11e7-9af2-65bbdc712ed3.png)

[Code to produce the above example](https://gist.github.com/jonmcalder/eb5243cb05ffeeeb27b41adabc1e6d4d)

With thanks to @jonocarroll whose prior effort paved the way and made this easy.

**Comment by hafen** [comment]
Awesome - thanks! I think this grid looks good. I have added it to the package with the example dataset.

I did make a couple changes to the codes. I think it's best to stick to a standard, and I'm using ISO_3166: https://en.wikipedia.org/wiki/ISO_3166-2:ZA. From this, I made the following changes: GP -> GT, KZN -> NL. If there is good reason for the original codes, please let me know!

**Comment by jonmcalder** [comment]
Ok cool!  I had actually considered using the ISO codes, but for some reason I went with popular convention for the provincial codes (i.e. what they are frequently abbreviated/known as) and in hindsight that wasn't the most logical option. Thanks for correcting that!
