### ISSUE TITLE
new grid

### ISSUE THREAD

**Issue by marcospaollo** [hafen/geofacet#62]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row,col,code,name
1,2,NT,Northern Territory
1,3,QLD,Queensland
2,1,WA,Western Australia
2,2,SA,South Australia
2,3,NSW,New South Wales
3,4,ACT,Australian Capital Territory
3,3,VIC,Victoria
5,3,TAS,Tasmania
```

![map](http://www.john.chapman.name/Austral4.gif)

**Comment by hafen** [comment]
This grid is already available in the package as `aus_grid1`. I don't recall if it came from here and I forgot to close it.
