### ISSUE TITLE
Cantons of Switzerland

### ISSUE THREAD

**Issue by rastrau** [hafen/geofacet#63]
A grid of the 26 Swiss cantons. The layout of this grid is loosely based on the *Switzerland Tilemap* I made for [EBP](http://www.ebp.ch/en) ([GitHub repo](https://github.com/ernstbaslerpartner/Switzerland_Tilemap), [Blog post](http://geo.ebp.ch/2016/01/07/tilemap-der-schweiz/)). The Switzerland Tilemap distinguishes between full cantons and so-called half-cantons (AI/AR, BS/BL, NW/OW) and uses a slightly irregular layout &ndash; both of which are not (yet?) possible within geofacet.

This `geofacet`-grid:

![map](https://github.com/ernstbaslerpartner/Switzerland_Tilemap/raw/master/Cantons_of_Switzerland_geofacet.png)

The original *Switzerland Tilemap*:

![image](https://user-images.githubusercontent.com/4510815/29034578-0485df5c-7b99-11e7-9ff8-67a7b687de12.png)

This grid features the commonly used two-letter canton abbreviations (e.g. GE, ZH) as well as the cantons' local names, names in German, French, Italian and English. In some cases, different spellings exist; I tried to include the most standard spellings in the data.

Grid data:

```
ID,Name_Local,Name_DE,Name_FR,Name_IT,Name_EN,row,col
SH,Schaffhausen,Schaffhausen,Schaffhouse,Sciaffusa,Schaffhausen,2,6
BS,Basel-Stadt,Basel-Stadt,Bâle-Ville,Basilea Città,Basel-City,2,4
TG,Thurgau,Thurgau,Thurgovie,Turgovia,Thurgovia,3,7
AG,Aargau,Aargau,Argovie,Argovia,Argovia,3,5
JU,Jura,Jura,Jura,Jura,Jura,3,3
BL,Basel-Landschaft,Basel-Landschaft,Bâle-Campagne,Basilea Campagna,Basel-Country,3,4
ZH,Zürich,Zürich,Zurich,Zurigo,Zurich,3,6
AI,Appenzell-Innerrhoden,Appenzell-Innerrhoden,Appenzell Rhodes-Intérieures,Appenzello Interno,Appenzell Inner-Rhodes,3,8
VD,Vaud,Waadt,Vaud,Vaud,Vaud,4,2
NE,Neuchâtel,Neuenburg,Neuchâtel,Neuchâtel,Neuchâtel,4,3
SO,Solothurn,Solothurn,Soleure,Soletta,Solothurn,4,4
LU,Luzern,Luzern,Lucerne,Lucerna,Lucerne,4,5
ZG,Zug,Zug,Zoug,Zugo,Zug,4,6
SG,St.Gallen,St.Gallen,Saint-Gall,San Gallo,St.Gallen,4,7
AR,Appenzell-Ausserrhoden,Appenzell-Ausserrhoden,Appenzell Rhodes-Extérieures,Appenzello Esterno,Appenzell Outer-Rhodes,4,8
FR,Fribourg,Freiburg,Fribourg,Friburgo,Fribourg,5,3
BE,Bern,Bern,Berne,Berna,Bern,5,4
NW,Nidwalden,Nidwalden,Nidwald,Nidvaldo,Nidwalden,5,5
GE,Genève,Genf,Genève,Ginevra,Geneva,5,1
SZ,Schwyz,Schwyz,Schwytz,Svitto,Schwyz,5,6
GL,Glarus,Glarus,Glaris,Glarona,Glarus,5,7
GR,Graubünden,Graubünden,Grisons,Grigioni,Grisons,5,9
VS,Valais,Wallis,Valais,Vallese,Valais,6,3
OW,Obwalden,Obwalden,Obwald,Obvaldo,Obwalden,6,5
UR,Uri,Uri,Uri,Uri,Uri,6,6
TI,Ticino,Tessin,Tessin,Ticino,Ticino,7,6
```

**Comment by hafen** [comment]
Thanks! Added as `ch_cantons_grid2`.

To address your questions, geofacet does not support irregular or half-grids. Theoretically it could be possible to place things irregularly but that would add a great deal of complexity so I don't plan to support it unless someone else wants to :). For the half-grids, this goes against the visual principles behind this approach, in which you want to be giving the same size canvas to each geographic entity.
