### ISSUE TITLE
new grid: 'cocina_fortea'

### ISSUE THREAD

**Issue by dieza** [hafen/geofacet#64]
Graticule of Fortea's excavation at Cocina Cave

![fortea_grid](https://user-images.githubusercontent.com/3057651/29486589-07c6a930-84ea-11e7-9cc1-2acbc0f7041a.png)

Grid data:

```
"row","col","code","name"
1,17,"E6","E6"
1,16,"E5","E5"
1,15,"E4","E4"
1,14,"E3","E3"
1,13,"E2","E2"
2,17,"D6","D6"
2,16,"D5","D5"
2,15,"D4","D4"
2,14,"D3","D3"
2,13,"D2","D2"
3,17,"C6","C6"
3,16,"C5","C5"
3,15,"C4","C4"
3,14,"C3","C3"
3,13,"C2","C2"
4,17,"B6","B6"
4,16,"B5","B5"
4,15,"B4","B4"
4,14,"B3","B3"
4,13,"B2","B2"
5,17,"A6","A6"
5,16,"A5","A5"
5,15,"A4","A4"
5,14,"A3","A3"
5,13,"A2","A2"
6,3,"A'8'","A'8'"
6,2,"A'9'","A'9'"
6,1,"A'10'","A'10'"
7,3,"B'8'","B'8'"
7,2,"B'9'","B'9'"
```

**Comment by dieza** [comment]
I'm trying to use my own data with this grid but I don't see a way of using it in my environment. It seems that only online grid can be used but maybe I'm missing something obvious.

**Comment by hafen** [comment]
You should be able to use any grid you can come up with locally. It appears based on the output plot you attached that you are able to use the grid in R. Could you provide some details on the error you are seeing or the plot you are trying to make?

**Comment by dieza** [comment]
Thanks for the package,
It was a silly mistake I was trying to load my grid between quotations `grid="mygrid"` (the way to go for the package grids) instead of `grid=mygrid`. Just in case, can I humbly suggest to add an example, even if it obvious, loading a local grid.
Cheers
