### ISSUE TITLE
new grid: 'spain_prov_grid1'

### ISSUE THREAD

**Issue by kintero** [hafen/geofacet#65]
Grid layout for the provinces of Spain

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name"
2,6,"01","Álava"
6,7,"02","Albacete"
6,8,"03","Alicante"
7,7,"04","Almería"
4,5,"05","Ávila"
6,4,"06","Badajoz"
4,12,"07","Balears, Illes"
3,10,"08","Barcelona"
3,6,"09","Burgos"
5,4,"10","Cáceres"
8,5,"11","Cádiz"
5,9,"12","Castellón"
6,6,"13","Ciudad Real"
6,5,"14","Córdoba"
1,2,"15","Coruña, A"
5,7,"16","Cuenca"
2,10,"17","Girona"
8,7,"18","Granada"
4,7,"19","Guadalajara"
1,7,"20","Gipuzkoa"
7,4,"21","Huelva"
2,8,"22","Huesca"
7,6,"23","Jaén"
2,4,"24","León"
2,9,"25","Lleida"
3,7,"26","Rioja, La"
1,3,"27","Lugo"
5,6,"28","Madrid"
8,6,"29","Málaga"
7,8,"30","Murcia"
2,7,"31","Navarra"
2,3,"32","Ourense"
1,4,"33","Asturias"
2,5,"34","Palencia"
9,2,"35","Palmas, Las"
2,2,"36","Pontevedra"
4,4,"37","Salamanca"
10,1,"38","S.C. Tenerife"
1,5,"39","Cantabria"
4,6,"40","Segovia"
7,5,"41","Sevilla"
3,8,"42","Soria"
4,9,"43","Tarragona"
4,8,"44","Teruel"
5,5,"45","Toledo"
5,8,"46","Valencia"
3,5,"47","Valladolid"
1,6,"48","Bizkaia"
3,4,"49","Zamora"
3,9,"50","Zaragoza"
10,5,"51","Ceuta"
10,6,"52","Melilla"
```

**Comment by kintero** [comment]
![spain_facet_unemployment_ts](https://user-images.githubusercontent.com/8983258/29547474-266dcbf4-86c8-11e7-8b2d-8547ec34ce23.jpg)

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/30039555-930879ca-9187-11e7-83ec-c1bebc985cac.png)

**Comment by kintero** [comment]
Beautiful! But, I think the following would be a little more specific. https://en.wikipedia.org/wiki/Provinces_of_Spain#/media/File:Provinces_of_Spain.svg 

The codes correspond with the codes used by the National Statistics Institute of Spain. You can find them here: http://www.ine.es/en/daco/daco42/codmun/cod_provincia_en.htm

Thank you for this amazing library.

**Comment by hafen** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Provinces_of_Spain.svg/569px-Provinces_of_Spain.svg.png

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/30189589-cbfbf2de-93e9-11e7-9598-bb4c4e09e0c1.png)

**Comment by hafen** [comment]
Thanks! Added as `spain_prov_grid1`

**Comment by kintero** [comment]
Hi Hafen,
Just to append license requirement of reference map according to https://commons.wikimedia.org/wiki/File:Provinces_of_Spain.svg.
**Author or credits:** Javitomad (https://en.wikipedia.org/wiki/User:Javitomad)
Regards
