### ISSUE TITLE
Sample dataset for Nigeria

### ISSUE THREAD

**Issue by BenChidi** [hafen/geofacet#66]
Please find attached sample dataset for Nigeria.

Regards.

Chidi

[nigeria_griddata_sample.xlsx](https://github.com/hafen/geofacet/files/1287864/nigeria_griddata_sample.xlsx)

**Comment by stedy** [comment]
Hi this appears to be data for different States in Nigeria, can you please add row and column codes? Use https://hafen.github.io/grid-designer/ as a design template
