### ISSUE TITLE
png grapics device

### ISSUE THREAD

**Issue by stagraph** [hafen/geofacet#67]
Hi, I have one problem.

I'm using the following script:
```
require(geofacet)
Plot1<- ggplot(data=state_ranks, aes(x=variable, y=rank, fill=variable)) +
geom_col(position=position_stack(vjust=1, reverse=FALSE), na.rm=FALSE, inherit.aes=TRUE) + 
facet_geo(~state)  

png(filename="C:/Users/admin/Desktop/sample.png", width=1664,height=1033.04,units = c("px"), res=96)
plot(Plot1)
dev.off()
``` 
Image file is created without any error message, but in the result image are also rendered empty sub-plots (panels) that are not defined in grid (e.g. plot on position "row 1 - column 1"). In the case I create this plot in window() graphical device, empty panels are not rendered. 

Is it possible to hide these panels in any way when I use png device?

**Comment by hafen** [comment]
If you use `print()` instead of `plot()`, it will work. I just added in a plot method as well so your above code will also work if you install from github.

**Comment by stagraph** [comment]
Thank you.
