### ISSUE TITLE
New grid: Swedish counties (version 2)

### ISSUE THREAD

**Issue by richardohrvall** [hafen/geofacet#68]
Hi, thanks for a great package. There is already a grid for Swedish counties, but I think the ordering of the counties could be improved. Furthermore, the county codes usually used in Swedish official statistics are 2 digit numbers (with zero padding), so I think it would be useful with a grid that follows that standard. I use the following to create such a grid, but it would be great if it could be included in the package. 

se_counties_grid2  <- tribble(~code, ~row, ~col, ~name,
                           "01", 6, 4, "Stockholm",
                           "03", 5, 3, "Uppsala",
                           "04", 6, 3, "Södermanland",
                           "05", 7, 3, "Östergötland",
                           "06", 8, 2, "Jönköping",
                           "07", 9, 2, "Kronoberg",
                           "08", 8, 3, "Kalmar",
                           "09", 8, 5, "Gotland",
                           "10", 9, 3, "Blekinge",
                           "12", 10, 2, "Skåne",
                           "13", 8, 1, "Halland",
                           "14", 7, 1, "Västra Götaland",
                           "17", 6, 1, "Värmland",
                           "18", 6, 2, "Örebro",
                           "19", 5, 2, "Västmanland",
                           "20", 4, 2, "Dalarna",
                           "21", 4, 3, "Gävleborg",
                           "22", 3, 3, "Västernorrland",
                           "23", 3, 2, "Jämtland",
                           "24", 2, 3, "Västerbotten",
                           "25", 1, 3, "Norrbotten")

All the best,
Richard

**Comment by richardohrvall** [comment]
Sorry, I saw that you wanted an example. This is how it looks with my suggested grid.
![old_county_geo2](https://user-images.githubusercontent.com/6022947/31674013-f700fca4-b360-11e7-8524-1d2e04d6f80f.png)

**Comment by richardohrvall** [comment]
And this is how the counties look on a map.

![200px-sweden_provinces_and_counties_overlayed svg](https://user-images.githubusercontent.com/6022947/31674109-45718e30-b361-11e7-8a2e-897ec335ce5a.png)

**Comment by richardohrvall** [comment]
And this is how the counties look on a map.
![karta-oever-sveriges-laen](https://user-images.githubusercontent.com/6022947/31674182-71150350-b361-11e7-9873-ffe319344c90.jpg)

**Comment by richardohrvall** [comment]
And this is how it looks when using the current grid that is already included in the package, i.e. se_counties_grid1.
![default_county](https://user-images.githubusercontent.com/6022947/31674353-e93cc390-b361-11e7-8a17-cee0122e5036.png)

**Comment by hafen** [comment]
Thanks! This has been added.
