### ISSUE TITLE
UK regions/NUTS1 areas

### ISSUE THREAD

**Issue by paulb20** [hafen/geofacet#69]
The UK regions aka EU standard NUTS 1 areas

Grid data:

```
row,col,name
1,2,Scotland
2,1,Northern Ireland
2,3,North East
3,2,North West
3,3,Yorkshire & the Humber
4,3,East Midlands
5,2,Wales
5,4,Eastern
5,3,West Midlands
6,2, South West
6,3, London
6,4, South East
```

![map](https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_the_United_Kingdom#/media/File:NUTS_1_statistical_regions_of_the_United_Kingdom_map.svg)

**Comment by hafen** [comment]
Adding reference image:

![uk-regional-map](https://user-images.githubusercontent.com/1275592/32032394-d394b24a-b9bb-11e7-91e8-fe4da69ba005.jpg)

**Comment by hafen** [comment]
Thanks! This has been added.
