### ISSUE TITLE
Honor faceting variables with layer-specific datasets

### ISSUE THREAD

**Issue by hafen** [hafen/geofacet#71]
It would be good for any `facet_geo()` faceting variables to be honored with layer-specific datasets in addition to the overall plot dataset. A good example of this is in #70. The same functionality would be nice for trelliscopejs. @schloerke, do you have any quick impressions about this?

**Comment by schloerke** [comment]
If it is possible to build the plot internally as a `facet_wrap`, then cherry pick each of the gtables of scales and panels, then there should be no worry.   The final product should be valid, as it was built from a facet_wrap.    This would take one regular (large) building, a panel shuffling, and a single printing, but a lot of logic.

This should be fine for trelliscopejs scales if the data is in memory.  trelliscopjs is a little different in that each panel is displayed independently.  For ggplot2, we could print a single, giant facet_wrap and then splice and dice into a shell plot.  Would be O(1) (very large single build) + O(1) (shell plot) for building and O(n) for printing.  Still 1/2 the time it currently takes of building and printing all N plots.

trelliscopejs could prolly be cleaned up with this idea.

**Comment by hafen** [comment]
This is fixed now in https://github.com/hafen/geofacet/commit/a735e285179477123262d228e1c855c02bb6f65f.
