### ISSUE TITLE
new grid: 'Districts of the Canton of Aargau'

### ISSUE THREAD

**Issue by zumbov2** [hafen/geofacet#75]
Districts of the Canton of Aargau

![districts_aargau](https://user-images.githubusercontent.com/31518032/32281394-fcd761d0-bf1e-11e7-9dcc-ae52307eeafd.png)

Grid data:

```
"name","code","row","col"
"Aarau",1901,2,2
"Baden",1902,2,4
"Bremgarten",1903,3,4
"Brugg",1904,1,3
"Kulm",1905,3,2
"Laufenburg",1906,1,2
"Lenzburg",1907,2,3
"Muri",1908,4,4
"Rheinfelden",1909,1,1
"Zofingen",1910,3,1
"Zurzach",1911,1,4
```

**Comment by hafen** [comment]
Thanks! This has been added as `ch_aargau_districts_grid1`.
