### ISSUE TITLE
world grid is crashing

### ISSUE THREAD

**Issue by synikitin** [hafen/geofacet#76]
Hello,

geofacet crashes with the following error when using the world grid: 

> Error in grepl(pattern, x$layout$name, fixed = fixed) : 
  invalid regular expression '(^background$|^panel-2-1$|^panel-4-1$|^panel-26-1$|^panel-11-2$|^panel-13-2$|^panel-29-2$|^panel-30-2$...

Here is a reproducible example (I have the github version of geofacet).

```
library(dplyr)
library(ggplot2)
library(geofacet)

df = data.frame(
  n = c(1, 1, 1),
  x = c(1, 1, 1),
  name = c("Austria", "Lebanon", "Greece"),
  code = c("AUT", "LBN", "GRC")
)

ggplot(df, aes(x, n)) + 
  facet_geo(~ code, grid = "world_86countries_grid", label = "name") +
  geom_col(width = .25, fill = "orange", color = "gray") +
  geom_text(aes(x, 200, label = n), size = 6, color = "magenta") +
  scale_x_continuous(labels = NULL, breaks = NULL) +
  labs(x = NULL, y = "Number of Attendies") +
  theme_bw() +
  theme(panel.background = element_rect(fill = "black"), panel.grid = element_blank())
```

I tried some other grids and it works fine.  Any ideas?

**Comment by hafen** [comment]
Thanks for the reproducible example. This should be fixed now.
