### ISSUE TITLE
new grid: 'nhs_scot_grid'

### ISSUE THREAD

**Issue by josephjosephadams** [hafen/geofacet#8]
Geofacet grid for the 14 health boards of [NHS Scotland](https://en.wikipedia.org/wiki/NHS_Scotland).

[Example code](https://gist.github.com/josephjosephadams/f83cda8768e760e24fd2bfc20f1af7a0)

Geocodes from [ONS (Office of National Statistics)](http://geoportal.statistics.gov.uk/datasets/61dca36aa33e4aee99bbfa784fa9eb25_0?uiTab=table). 
Data from the [Scottish Government](http://statistics.gov.scot/data/child-dental-health). 
Map from [NHS Education for Scotland ](http://www.nes.scot.nhs.uk/education-and-training/by-discipline/nursing-and-midwifery/practice-education/nursing-and-midwifery-practice-educators.aspx) (note of warning: for convenience, maps like below often place Orkney and Shetland closer to the mainland than reality).

```
~code, ~row, ~col, ~name,
"S08000015", 6, 1, "Ayrshire and Arran",
"S08000016", 6, 3, "Borders",
"S08000017", 6, 2, "Dumfries and Galloway",
"S08000018", 4, 3, "Fife",
"S08000019", 4, 2, "Forth Valley",
"S08000020", 2, 2, "Grampian",
"S08000021", 5, 1, "Greater Glasgow and Clyde",
"S08000022", 3, 1, "Highland",
"S08000023", 5, 2, "Lanarkshire",
"S08000024", 5, 3, "Lothian",
"S08000025", 1, 2, "Orkney",
"S08000026", 1, 3, "Shetland",
"S08000027", 3, 2, "Tayside",
"S08000028", 2, 1, "Western Isle"
```

![image](https://cloud.githubusercontent.com/assets/24879214/26426113/253658d0-40cf-11e7-88b5-fe5ee7fda44f.png)

![image](https://cloud.githubusercontent.com/assets/24879214/26425914/793638f2-40ce-11e7-98c6-f00afc73540f.png)

**Comment by hafen** [comment]
Added. Thanks!
