### ISSUE TITLE
Jordan 12 governatorates

### ISSUE THREAD

**Issue by ghosthedirewolf** [hafen/geofacet#80]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
row,col,code,name
1,1, JOR1, Irbid
2,1, JOR5, Balqa
2,4, JOR4, Mafraq
2,2, JOR2, Ajloun
2,3, JOR3, Jerash
3,2, JOR6, Amman
3,1, JOR8, Madaba
3,3, JOR7, Zarqa
4,1, JOR9, Karak
5,1, JOR10, Tafilah
4,2, JOR11, Ma'an
6,1, JOR12, Aqaba
```

![map](http://www.24point0.com/ppt-shop/media/catalog/product/cache/1/image/a147e053e38da8d26dbbb3bb24b21280/j/o/jordan-governorate-capitals-map-powerpoint-presentation.jpg)

**Comment by hafen** [comment]
Thanks! This has been added.

**Comment by hafen** [comment]
![image](https://user-images.githubusercontent.com/1275592/82837533-32964c00-9e7e-11ea-841f-8ab3a202b888.png)
