### ISSUE TITLE
China_city_Grid

### ISSUE THREAD

**Issue by CharleneDeng1** [hafen/geofacet#81]
Hi, hefan

below are part of China cities,  would you mind save those as "China_city_Grid" Thanks! : )

name <- c("Urumqi",	"Harbin",	"Mudanjiang",	"Jilin",	"Changchun",	" Shenyang",	" Dalian",	"Tianjin",	" Beijing",	" Hohhot",	"Yantai",	" Qingdao",	"Jining",	" Jinan",	"Shijiazhuang",	"Taiyuan",	"Yinchuan",	"Lanzhou",	" Xining",	"Wuxi",	"Xuzhou",	"Zhengzhou",	"Luoyang",	" Xi'an",	"Nanjing",	"Hefei",	"Shanghai",	" Yangzhou",	" Hangzhou",	"Wenzhou",	" Ningbo",	" Jiujiang",	" Wuhan",	"Fuzhou",	" Quanzhou",	" Changsha",	"Nanchang",	" Chongqing",	"Chengdu",	"Ganzhou",	" Xiamen",	" Kunming",	" Guiyang",	" Shenzhen",	"Nanning",	" Guangzhou",	" Haikou",	" Sanya")

code<- c("UMQ",	"HrB",	"MDJ",	"JL",	"CC",	"SY",	"DL",	"TJ",	"BJ",	"HHT",	"YT",	"QD",	"JiN",	"JN",	"SJZ",	"TY",	"YC",	"LZ",	"XN",	"WX",	"XZ",	"ZZ",	"LY",	"XA",	"NJ",	"HF",	"SH",	"YZ",	"HZ",	"WZ",	"NB",	"JJ",	"WH",	"FZ",	"QZ",	"CS",	"NC",	"CQ",	"CD",	"GAZ",	"XM",	"KM",	"GY",	"SZ",	"NN",	"GZ",	"HK",	"Sya")

row = c(1,	1,	1,	2,	2,	2,	2,	2,	2,	2,	3,	3,	3,	3,	3,	3,	3,	3,	3,	4,	4,	4,	4,	4,	5,	5,	5,	5,	6,	6,	6,	6,	6,	7,	7,	7,	7,	7,	7,	8,	8,	8,	8,	9,	9,	9,	9,	10)

col = c(1,	16,	15,	16,	15,	14,	13,	11,	10,	7,	13,	12,	11,	10,	9,	7,	5,	3,	2,	13,	11,	8,	7,	6,	11,	10,	13,	12,	11,	12,	13,	9,	8,	12,	11,	8,	9,	5,	4,	9,	11,	3,	5,	9,	6,	8,	7,	7)

China_city_Grid <- data.frame(name=name,code=code,row=row,col=col)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.

**Comment by hafen** [comment]
Every grid needs a reference map image. I'm not sure what to look for for this one, so I'm attaching a blank image to use as a placeholder for now.

![image](https://user-images.githubusercontent.com/1275592/82846130-3f299d00-9e9c-11ea-8a38-efb4ade0e502.png)
