### ISSUE TITLE
US Census Divisions

### ISSUE THREAD

**Issue by mkiang** [hafen/geofacet#82]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
code,name,row,col
NED,New England,1,6
WNC,West North Central,2,3
ENC,East North Central,2,4
MID,Middle Atlantic,2,5
MTN,Mountain,2,2
PAC,Pacific,2,1
WSC,West South Central,3,3
ESC,East South Central,3,4
SAT,South Atlantic,3,5
```

```
mygrid <- data.frame(
  code = c("NED", "WNC", "ENC", "MID", "MTN", "PAC", "WSC", "ESC", "SAT"),
  name = c("New England", "West North Central", "East North Central", "Middle Atlantic", "Mountain", "Pacific", "West South Central", "East South Central", "South Atlantic"),
  row = c(1, 2, 2, 2, 2, 2, 3, 3, 3),
  col = c(6, 3, 4, 5, 2, 1, 3, 4, 5),
  stringsAsFactors = FALSE
)
geofacet::grid_preview(mygrid)
```

![map](https://www.eia.gov/consumption/commercial/images/cendivco.gif)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
