### ISSUE TITLE
relax dependence on R version

### ISSUE THREAD

**Issue by shabbybanks** [hafen/geofacet#85]
The package currently requires R version 3.3.2:
```
Depends: R (>= 3.3.2)
```
For those of us locked into old versions of R, a less stringent dependency would be helpful. In a fork, I rolled this back to 3.2, and have installed and use the package. I can find no need for importing `backports` in the code (usually `trimws` is the offending function). I would be happy to submit a PR for the 1 line change, but it's probably not necessary.

**Comment by hafen** [comment]
I have relaxed it to 3.2.

**Comment by shabbybanks** [comment]
great! thanks! cool package, BTW.
