### ISSUE TITLE
kr_seoul_district_grid

### ISSUE THREAD

**Issue by yonghah** [hafen/geofacet#86]
Grid map of Seoul's 25 districts. 

Grid data:

```
name,row,col,code
도봉구,1,4,DB
노원구,1,5,NW
강북구,1,3,GB
은평구,2,3,EP
종로구,2,4,JOR
성북구,2,5,SB
중랑구,3,6,JUR
동대문구,3,5,DDM
중구,3,4,JG
서대문구,3,3,SDM
마포구,3,2,MP
강서구,4,1,GS
광진구,4,6,GJ
성동구,4,5,SD
영등포구,4,3,YDP
용산구,4,4,YS
양천구,4,2,YC
강동구,4,7,GD
동작구,5,3,DJ
송파구,5,6,SP
강남구,5,5,GN
구로구,5,2,GR
서초구,5,4,SC
관악구,6,3,GA
금천구,6,2,GC
```

![map](https://ko.wikipedia.org/wiki/%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C#/media/File:01-00-seoul-ko.svg)
https://ko.wikipedia.org/wiki/%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C#/media/File:01-00-seoul-ko.svg

**Comment by hafen** [comment]
<img width="641" alt="seouldistricts" src="https://user-images.githubusercontent.com/1275592/38068875-494e49a8-32c8-11e8-8ace-b91982fe486f.png">

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
