### ISSUE TITLE
new grid: Slovenian Regions

### ISSUE THREAD

**Issue by SR1986** [hafen/geofacet#88]
Grid: Slovenian Regions

Grid data:

```
row,col,code,name
1,4,KOROŠ,KOROŠKA REGIJA
1,6,POMUR,POMURSKA REGIJA
2,2,GOREN,GORENJSKA REGIJA
2,5,PODRA,PODRAVSKA REGIJA
2,4,SAVIN,SAVINJSKA REGIJA
3,2,GORIŠ,GORIŠKA REGIJA
3,3,OSRED,OSREDNJESLOVENSKA REGIJA
3,5,POSAV,POSAVSKA REGIJA
3,4,ZASAV,ZASAVSKA REGIJA
4,1,OBALN,OBALNO-KRAŠKA REGIJA
4,4,JUGOV,JUGOVZHODNA SLOVENIJA
4,2,PRIMO,PRIMORSKO-NOTRANJSKA REGIJA
```

structure(list(code = c("KOROŠ", "POMUR", "GOREN", "PODRA", "SAVIN", "GORIŠ", "OSRED", "POSAV", "ZASAV", "OBALN", "JUGOV", "PRIMO"),
               name = c("KOROŠKA REGIJA", "POMURSKA REGIJA", "GORENJSKA REGIJA", "PODRAVSKA REGIJA", "SAVINJSKA REGIJA", "GORIŠKA REGIJA", "OSREDNJESLOVENSKA REGIJA", "POSAVSKA REGIJA", "ZASAVSKA REGIJA", "OBALNO-KRAŠKA REGIJA", "JUGOVZHODNA SLOVENIJA", "PRIMORSKO-NOTRANJSKA REGIJA"),
               row = c(1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4), 
               col = c(4, 6, 2, 5, 4, 2, 3, 5, 4, 1, 4, 2)), .Names = c("code","name", "row", "col"), class = "data.frame", row.names = c(NA,-12L))

**Comment by SR1986** [comment]
Could you please accept the suggested grid (above) in github? Thank you in advance! Cheers!

**Comment by hafen** [comment]
![slovenia _administrative_divisions_-_de_ statistical_regions _-_colored svg](https://user-images.githubusercontent.com/1275592/38069181-df2cbcb0-32c9-11e8-8a5b-0528f3e9e81c.png)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.

**Comment by SR1986** [comment]
Thanks a lot for adding proposal of my grid. I have tried it out on sample data and it works perfectly :).
