### ISSUE TITLE
Idaho State County Map

### ISSUE THREAD

**Issue by hathawayj** [hafen/geofacet#91]
[[Note: Please edit the title above and provide a description of the grid here.
Also check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) 
codes if your grid uses countries or states/provinces. Finally, if you can 
provide an example of your grid in action with a data set and sample code, 
that would be great but is not required. Remove this text before submitting.]]

Grid data:

```
code_fip,name,row,col
021,Boundary,1,1
017,Bonner,2,1
055,Kootenai,3,1
079,Shoshone,3,2
009,Benewah,4,1
035,Clearwater,4,2
057,Latah,5,1
069,Nez Perce,5,2
059,Lemhi,6,4
061,Lewis,6,1
049,Idaho,6,2
043,Fremont,7,8
033,Clark,7,7
085,Valley,7,3
003,Adams,7,2
037,Custer,7,4
081,Teton,8,9
065,Madison,8,8
051,Jefferson,8,7
023,Butte,8,6
015,Boise,8,3
087,Washington,8,1
045,Gem,9,2
019,Bonneville,9,8
011,Bingham,9,7
013,Blaine,9,6
025,Camas,9,4
075,Payette,9,1
039,Elmore,9,3
063,Lincoln,10,5
047,Gooding,10,4
001,Ada,10,2
027,Canyon,10,1
053,Jerome,11,5
067,Minidoka,11,6
077,Power,11,7
005,Bannock,11,8
029,Caribou,11,9
007,Bear Lake,12,9
041,Franklin,12,8
071,Oneida,12,7
031,Cassia,12,6
083,Twin Falls,12,4
073,Owyhee,12,1
```

![map](https://geology.com/county-map/idaho-county-map.gif)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
