### ISSUE TITLE
Ciudad Autónoma de Buenos Aires (AR)

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#93]
Grid data:

```
code, name,row,col
13,13,1,3
12,12,1,2
11,11,2,1
14,14,2,3
15,15,2,2
2,2,2,4
6,6,3,2
10,10,3,1
5,5,3,3
3,3,3,4
7,7,4,2
9,9,4,1
1,1,3,5
4,4,4,3
8,8,5,2
```

![map](http://www.noticiariosur.com.ar/wp-content/uploads/2012/02/COMNAS-MAPA.gif)

**Comment by TuQmano** [comment]
@hafen I upload this Buenos Aires City grid design couple days ago and just uploaded TUCUMAN district as the second Argentina´s province. Thanks a lot for this great tool!

**Comment by hafen** [comment]
What are the regions of this map? Just checking for naming convention.

**Comment by TuQmano** [comment]
The city of Buenos Aires is formally divided in 48 barrios (neighbourhoods), grouped into 15 comunas (communes), which are defined as "units of decentralized political and administrative management governed by designated residents.

**Comment by TuQmano** [comment]
Example of 2017 national election in the district. Results by commune:

https://twitter.com/TuQmano/status/974649874011467778?s=09

**Comment by hafen** [comment]
Thanks! This has been added to the package.
