### ISSUE TITLE
new grid: 'poland_voivodeships_grid1'

### ISSUE THREAD

**Issue by erzk** [hafen/geofacet#95]
Polish voivodeships (provinces)

![poland_administrative_division_1999_literki](https://user-images.githubusercontent.com/5550348/37672220-69c03caa-2c65-11e8-857e-2955f25f55bf.png)

Grid data:

```
"name","code","row","col"
"Pomeranian","PM",1,3
"West Pomeranian","ZP",1,1
"Warmian-Masurian","WN",1,4
"Kuyavian-Pomeranian","KP",2,3
"Lubusz","LB",2,1
"Greater Poland","WP",2,2
"Podlaskie","PD",2,5
"Masovian","MZ",3,4
"Łódź","LD",3,3
"Lower Silesian","DS",3,1
"Opole","OP",4,2
"Holy Cross","SK",4,4
"Lublin","LU",4,5
"Silesian","SL",4,3
"Lesser Poland","MA",5,4
"Subcarpathian","PK",5,5
```

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
