### ISSUE TITLE
TUCUMAN (AR) 

### ISSUE THREAD

**Issue by TuQmano** [hafen/geofacet#96]
Tucumán Province (Argentina) political division. 

Source: [Wikipedia](https://en.wikipedia.org/wiki/Tucum%C3%A1n_Province#Political_division)

Grid data:

```
name,code,row,col
Trancas,2,1,3
Burruyacu,3,1,4
Tafi del Valle,1,2,1
Cruz Alta,7,2,5
Y.Buena,5,2,3
Capital,6,2,4
Tafi Viejo,4,2,2
Leales,11,3,5
Monteros,10,3,2
Famailla,9,3,3
Lules,8,3,4
Chicligasta,12,4,2
Rio Chico,14,4,3
Simoca,13,4,4
Graneros,16,5,4
J.B.Alberdi,15,5,3
La Cocha,17,6,3
```

![map](http://www.comollegara.com/images/argentina/departamentos-de-la-provincia-de-tucuman.png)

**Comment by TuQmano** [comment]
Hi @hafen  I recently upload Buenos Aires City grid -> https://github.com/hafen/geofacet/issues/93
In this turn I upload Tucumán Province political division (Departments). Thanks a lot. This is great!

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
