### ISSUE TITLE
new grid: 'cn_prov_grid1'

### ISSUE THREAD

**Issue by jw2531** [hafen/geofacet#97]
political map of China provinces

![china_provinces](https://user-images.githubusercontent.com/36669758/37746305-f5c138f4-2d4f-11e8-8a48-2a21513ea828.png)

Grid data:

```
"code","row","col","name"
"XJ",4,1,"XINJIANG"
"XZ",5,1,"TIBET"
"GS",4,2,"GANSU"
"QH",5,2,"QINGHAI"
"SC",6,2,"SICHUAN"
"YN",7,2,"YUNNAN"
"NX",5,3,"NINGXIA"
"CQ",6,3,"CHONGQING"
"GZ",7,3,"GUIZHOU"
"SX",4,4,"SHANXI"
"SN",5,4,"SHAANXI"
"HB",6,4,"HUBEI"
"HN",7,4,"HUNAN"
"GX",8,4,"GUANGXI"
"HI",9,4,"HAINAN"
"HE",4,5,"HEBEI"
"HN",5,5,"HENAN"
"AH",6,5,"ANHUI"
"JX",7,5,"JIANGXI"
"GD",8,5,"GUANGDONG"
"MO",9,5,"MACAU"
"NM",2,6,"INNER MONGOLIA"
"BJ",3,6,"BEIJING"
"TJ",4,6,"TIANJIN"
"SD",5,6,"SHANDONG"
"JS",6,6,"JIANGSU"
"ZJ",7,6,"ZHEJIANG"
"FJ",8,6,"FUJIAN"
"HK",9,6,"HONG KONG"
"HL",1,7,"HEILONGJIANG"
"JL",2,7,"JILIN"
"LN",3,7,"LIAONING"
"SH",6,7,"SHANGHAI"
"TW",8,7,"TAIWAN"
```

**Comment by jw2531** [comment]
Don't know why the link to the actual map doesn't work.

**Comment by jw2531** [comment]
Updated the codes using GB/T 2260-2007.

**Comment by jw2531** [comment]
![china_provinces](https://user-images.githubusercontent.com/36669758/37746264-c6b0c926-2d4f-11e8-8ac5-d637e42ac186.png)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
