### ISSUE TITLE
New Hampshire grid

### ISSUE THREAD

**Issue by soungl** [hafen/geofacet#98]
[[Note: 10 counties in New Hampshire.]]

Grid data:

```
name,row,col,code
Coos,1,3,Co
Grafton,2,1,Gr 
Carroll,2,3,Ca
Belknap,2,2,Be
Sullivan,3,1,Su
Merrimack,3,2,Me
Strafford,3,3,St
Cheshire,4,1,Ch
Hillsborough,4,2,Hi
Rockingham,4,3,Ro 
```

![map](https://en.wikipedia.org/wiki/List_of_counties_in_New_Hampshire#/media/File:New_Hampshire_Locator_Map.PNG)

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
