### ISSUE TITLE
new grid: 'nh_grid'

### ISSUE THREAD

**Issue by soungl** [hafen/geofacet#99]
10 counties in New Hampshire

[[https://en.wikipedia.org/wiki/List_of_counties_in_New_Hampshire#/media/File:New_Hampshire_Locator_Map.PNG]]

Grid data:

```
"name","code","row","col"
"Coos","Co",1,3
"Grafton","Gr",2,1
"Carroll","Ca",2,3
"Belknap","Be",2,2
"Sullivan","Su",3,1
"Merrimack","Me",3,2
"Strafford","St",3,3
"Cheshire","Ch",4,1
"Hillsborough","Hi",4,2
"Rockingham","Ro",4,3
```

**Comment by hafen** [comment]
This has been added to the package on github and will be part of the next CRAN release. Thanks for contributing.
